In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def ANN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    clf = MLPClassifier(activation = 'logistic', hidden_layer_sizes=(150))
    
    clf.fit(X_train, Y_train_binary)
    Y_pred = clf.predict(X_test)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
ANN(path_train,path_test)

[[39  3]
 [12 37]]
              precision    recall  f1-score   support

           0       0.93      0.76      0.84        51
           1       0.76      0.93      0.83        40

    accuracy                           0.84        91
   macro avg       0.84      0.84      0.84        91
weighted avg       0.85      0.84      0.84        91



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
ANN(path_train,path_test)

[[ 3  1]
 [10 46]]
              precision    recall  f1-score   support

           0       0.75      0.23      0.35        13
           1       0.82      0.98      0.89        47

    accuracy                           0.82        60
   macro avg       0.79      0.60      0.62        60
weighted avg       0.81      0.82      0.78        60



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
ANN(path_train,path_test)

[[53  9]
 [ 4 23]]
              precision    recall  f1-score   support

           0       0.85      0.93      0.89        57
           1       0.85      0.72      0.78        32

    accuracy                           0.85        89
   macro avg       0.85      0.82      0.84        89
weighted avg       0.85      0.85      0.85        89



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
ANN(path_train,path_test)

[[ 0  0]
 [ 2 35]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.95      1.00      0.97        35

    accuracy                           0.95        37
   macro avg       0.47      0.50      0.49        37
weighted avg       0.89      0.95      0.92        37



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python

# Europe

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
ANN(path_train,path_test)

[[54 10]
 [ 5 57]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88        59
           1       0.92      0.85      0.88        67

    accuracy                           0.88       126
   macro avg       0.88      0.88      0.88       126
weighted avg       0.88      0.88      0.88       126



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
ANN(path_train,path_test)

[[ 98  18]
 [ 24 136]]
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       122
           1       0.85      0.88      0.87       154

    accuracy                           0.85       276
   macro avg       0.85      0.84      0.84       276
weighted avg       0.85      0.85      0.85       276



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
