In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def CNN(path_train,path_test,name,epoch_num):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(22,1)))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Flatten())
    model.add(Dense(16, activation='relu'))
    model.add(Dense(2, activation='sigmoid'))

    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=epoch_num, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

    model_name = f'{name}_cnn.h5'
    model.save('../Models/CNN_only/' + model_name)
    
    mismatch = [i for i, (a,b) in enumerate(zip(Y_pred, Y_test_binary)) if a != b]
    print(mismatch)
            
    return model

# Cleveland

In [3]:
path_train = '../TrainTestData/cle_train.csv'
path_test = '../TrainTestData/cle_test.csv'
model = CNN(path_train,path_test,'cle',20)

Epoch 1/20
7/7 [==============================] - 2s 21ms/step - loss: 0.6398 - accuracy: 0.6321
Epoch 2/20
7/7 [==============================] - 0s 24ms/step - loss: 0.5208 - accuracy: 0.7642
Epoch 3/20
7/7 [==============================] - 0s 18ms/step - loss: 0.4605 - accuracy: 0.8019
Epoch 4/20
7/7 [==============================] - 0s 15ms/step - loss: 0.4261 - accuracy: 0.7972
Epoch 5/20
7/7 [==============================] - 0s 17ms/step - loss: 0.4314 - accuracy: 0.8019
Epoch 6/20
7/7 [==============================] - 0s 17ms/step - loss: 0.3726 - accuracy: 0.8302
Epoch 7/20
7/7 [==============================] - 0s 18ms/step - loss: 0.3524 - accuracy: 0.8538
Epoch 8/20
7/7 [==============================] - 0s 20ms/step - loss: 0.3456 - accuracy: 0.8443
Epoch 9/20
7/7 [==============================] - 0s 18ms/step - loss: 0.3297 - accuracy: 0.8632
Epoch 10/20
7/7 [==============================] - 0s 15ms/step - loss: 0.3148 - accuracy: 0.8679
Epoch 11/20
7/7 [============

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
CNN(path_train,path_test,'vir',10)

Epoch 1/10
5/5 [==============================] - 1s 19ms/step - loss: 0.6118 - accuracy: 0.7286
Epoch 2/10
5/5 [==============================] - 0s 17ms/step - loss: 0.5852 - accuracy: 0.7286
Epoch 3/10
5/5 [==============================] - 0s 14ms/step - loss: 0.5530 - accuracy: 0.7286
Epoch 4/10
5/5 [==============================] - 0s 17ms/step - loss: 0.5520 - accuracy: 0.7286
Epoch 5/10
5/5 [==============================] - 0s 20ms/step - loss: 0.5338 - accuracy: 0.7286
Epoch 6/10
5/5 [==============================] - 0s 13ms/step - loss: 0.5258 - accuracy: 0.7286
Epoch 7/10
5/5 [==============================] - 0s 17ms/step - loss: 0.5171 - accuracy: 0.7286
Epoch 8/10
5/5 [==============================] - 0s 18ms/step - loss: 0.5071 - accuracy: 0.7286
Epoch 9/10
5/5 [==============================] - 0s 17ms/step - loss: 0.4976 - accuracy: 0.7286
Epoch 10/10
5/5 [==============================] - 0s 14ms/step - loss: 0.4882 - accuracy: 0.7357
[[ 2  0]
 [11 47]]
          

# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
CNN(path_train,path_test,'hun',20)

Epoch 1/20
7/7 [==============================] - 1s 16ms/step - loss: 0.6337 - accuracy: 0.5756
Epoch 2/20
7/7 [==============================] - 0s 18ms/step - loss: 0.5046 - accuracy: 0.8195
Epoch 3/20
7/7 [==============================] - 0s 17ms/step - loss: 0.4615 - accuracy: 0.7854
Epoch 4/20
7/7 [==============================] - 0s 17ms/step - loss: 0.4047 - accuracy: 0.8244
Epoch 5/20
7/7 [==============================] - 0s 17ms/step - loss: 0.3560 - accuracy: 0.8488
Epoch 6/20
7/7 [==============================] - 0s 16ms/step - loss: 0.3337 - accuracy: 0.8634
Epoch 7/20
7/7 [==============================] - 0s 17ms/step - loss: 0.3118 - accuracy: 0.8683
Epoch 8/20
7/7 [==============================] - 0s 19ms/step - loss: 0.3202 - accuracy: 0.8390
Epoch 9/20
7/7 [==============================] - 0s 18ms/step - loss: 0.2754 - accuracy: 0.8878
Epoch 10/20
7/7 [==============================] - 0s 17ms/step - loss: 0.2887 - accuracy: 0.8976
Epoch 11/20
7/7 [============

# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
CNN(path_train,path_test,'swi',10)

Epoch 1/10
3/3 [==============================] - 1s 20ms/step - loss: 0.6549 - accuracy: 0.6279
Epoch 2/10
3/3 [==============================] - 0s 19ms/step - loss: 0.4188 - accuracy: 0.9302
Epoch 3/10
3/3 [==============================] - 0s 18ms/step - loss: 0.2758 - accuracy: 0.9302
Epoch 4/10
3/3 [==============================] - 0s 14ms/step - loss: 0.2637 - accuracy: 0.9302
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 0.2919 - accuracy: 0.9302
Epoch 6/10
3/3 [==============================] - 0s 14ms/step - loss: 0.2764 - accuracy: 0.9302
Epoch 7/10
3/3 [==============================] - 0s 15ms/step - loss: 0.2511 - accuracy: 0.9302
Epoch 8/10
3/3 [==============================] - 0s 23ms/step - loss: 0.2483 - accuracy: 0.9302
Epoch 9/10
3/3 [==============================] - 0s 16ms/step - loss: 0.2424 - accuracy: 0.9302
Epoch 10/10
3/3 [==============================] - 0s 22ms/step - loss: 0.2425 - accuracy: 0.9302
[[ 0  0]
 [ 2 35]]
          

c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Europe

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
CNN(path_train,path_test,'eur',20)

Epoch 1/20
10/10 [==============================] - 2s 18ms/step - loss: 0.6239 - accuracy: 0.6254
Epoch 2/20
10/10 [==============================] - 0s 17ms/step - loss: 0.4859 - accuracy: 0.8144
Epoch 3/20
10/10 [==============================] - 0s 16ms/step - loss: 0.3893 - accuracy: 0.8316
Epoch 4/20
10/10 [==============================] - 0s 16ms/step - loss: 0.3554 - accuracy: 0.8454
Epoch 5/20
10/10 [==============================] - 0s 16ms/step - loss: 0.3657 - accuracy: 0.8213
Epoch 6/20
10/10 [==============================] - 0s 15ms/step - loss: 0.3272 - accuracy: 0.8522
Epoch 7/20
10/10 [==============================] - 0s 16ms/step - loss: 0.3549 - accuracy: 0.8625
Epoch 8/20
10/10 [==============================] - 0s 14ms/step - loss: 0.3060 - accuracy: 0.8729
Epoch 9/20
10/10 [==============================] - 0s 15ms/step - loss: 0.3344 - accuracy: 0.8660
Epoch 10/20
10/10 [==============================] - 0s 14ms/step - loss: 0.2813 - accuracy: 0.8969
Epoch 11/

# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
CNN(path_train,path_test,'com',20)

Epoch 1/20
21/21 [==============================] - 1s 15ms/step - loss: 0.6809 - accuracy: 0.5435
Epoch 2/20
21/21 [==============================] - 0s 15ms/step - loss: 0.6367 - accuracy: 0.6413
Epoch 3/20
21/21 [==============================] - 0s 15ms/step - loss: 0.5201 - accuracy: 0.7826
Epoch 4/20
21/21 [==============================] - 0s 15ms/step - loss: 0.4496 - accuracy: 0.8059
Epoch 5/20
21/21 [==============================] - 0s 16ms/step - loss: 0.4502 - accuracy: 0.7981
Epoch 6/20
21/21 [==============================] - 0s 16ms/step - loss: 0.4250 - accuracy: 0.8168
Epoch 7/20
21/21 [==============================] - 0s 15ms/step - loss: 0.4196 - accuracy: 0.8261
Epoch 8/20
21/21 [==============================] - 0s 15ms/step - loss: 0.4191 - accuracy: 0.8292
Epoch 9/20
21/21 [==============================] - 0s 15ms/step - loss: 0.4092 - accuracy: 0.8354
Epoch 10/20
21/21 [==============================] - 0s 17ms/step - loss: 0.4018 - accuracy: 0.8292
Epoch 11/

In [9]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'

In [10]:
Train = pd.read_csv(path_train)
Test = pd.read_csv(path_test)
    
X_train = Train.iloc[:,:-1]
Y_train = Train.iloc[:,-1]

X_test = Test.iloc[:,:-1]
Y_test = Test.iloc[:,-1]

#binarize the target
Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

data = pd.concat([X_train,X_test])
labels = pd.concat([Y_train_binary,Y_test_binary])

data = data.reset_index()
data = data.drop(['index'],axis = 1)

labels = labels.reset_index()
labels = labels.iloc[:,-1]

labels

0      0
1      1
2      0
3      0
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: num, Length: 417, dtype: int64

In [11]:
Y_pred = model.predict(data).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, labels)
print(cm)
print(classification_report(labels, Y_pred))

[[118  18]
 [ 78 203]]
              precision    recall  f1-score   support

           0       0.87      0.60      0.71       196
           1       0.72      0.92      0.81       221

    accuracy                           0.77       417
   macro avg       0.80      0.76      0.76       417
weighted avg       0.79      0.77      0.76       417

