In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def RandomForest(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = RandomForestClassifier(n_estimators=100, random_state=42)
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [2]:
train = pd.read_csv('../traintestdata/cle_train.csv')
test = pd.read_csv('../traintestdata/cle_test.csv')

cle = pd.concat([train,test])

In [3]:
cle

cp_1.0  cp_2.0  cp_3.0  cp_4.0  restecg_0.0  restecg_1.0  restecg_2.0  \
0      0.0     0.0     0.0     1.0          1.0          0.0          0.0   
1      1.0     0.0     0.0     0.0          1.0          0.0          0.0   
2      0.0     0.0     1.0     0.0          0.0          0.0          1.0   
3      0.0     1.0     0.0     0.0          0.0          0.0          1.0   
4      0.0     0.0     0.0     1.0          0.0          0.0          1.0   
..     ...     ...     ...     ...          ...          ...          ...   
86     0.0     0.0     0.0     1.0          0.0          0.0          1.0   
87     0.0     0.0     1.0     0.0          0.0          0.0          1.0   
88     0.0     0.0     0.0     1.0          1.0          0.0          0.0   
89     0.0     0.0     1.0     0.0          0.0          0.0          1.0   
90     0.0     0.0     0.0     1.0          1.0          0.0          0.0   

    slope_1.0  slope_2.0  slope_3.0  ...       age  sex  trestbps      chol  \
0         1.0        0.0        0.0  ...  0.791667  0.0  0.113208  0.221461   
1         0.0        1.0        0.0  ...  0.479167  1.0  0.547170  0.392694   
2         1.0        0.0        0.0  ...  0.458333  0.0  0.245283  0.385845   
3         1.0        0.0        0.0  ...  0.854167  1.0  0.584906  0.271689   
4         0.0        1.0        0.0  ...  0.687500  0.0  0.433962  0.611872   
..        ...        ...        ...  ...       ...  ...       ...       ...   
86        0.0        1.0        0.0  ...  0.583333  1.0  0.528302  0.342466   
87        0.0        1.0        0.0  ...  0.770833  0.0  0.490566  0.347032   
88        1.0        0.0        0.0  ...  0.270833  1.0  0.433962  0.228311   
89        0.0        1.0        0.0  ...  0.791667  1.0  0.547170  0.196347   
90        0.0        1.0        0.0  ...  0.604167  0.0  0.339623  0.162100   

    fbs   thalach  exang   oldpeak        ca   num  
0   0.0  0.541985    0.0  0.048387  0.666667  0.00  
1   1.0  0.816794    0.0  0.193548  0.000000  0.00  
2   0.0  0.656489    0.0  0.096774  0.000000  0.00  
3   0.0  0.549618    0.0  0.000000  0.000000  0.00  
4   0.0  0.656489    0.0  0.193548  0.000000  0.00  
..  ...       ...    ...       ...       ...   ...  
86  0.0  0.312977    1.0  0.096774  0.333333  0.25  
87  0.0  0.618321    0.0  0.000000  0.333333  0.00  
88  0.0  0.816794    0.0  0.000000  0.000000  0.00  
89  0.0  0.603053    0.0  0.129032  0.000000  0.25  
90  0.0  0.458015    0.0  0.096774  0.000000  0.00  

[303 rows x 23 columns]

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
RandomForest(path_train,path_test)

[[41  5]
 [10 35]]
              precision    recall  f1-score   support

           0       0.89      0.80      0.85        51
           1       0.78      0.88      0.82        40

    accuracy                           0.84        91
   macro avg       0.83      0.84      0.83        91
weighted avg       0.84      0.84      0.84        91



# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
RandomForest(path_train,path_test)

[[ 6  3]
 [ 7 44]]
              precision    recall  f1-score   support

           0       0.67      0.46      0.55        13
           1       0.86      0.94      0.90        47

    accuracy                           0.83        60
   macro avg       0.76      0.70      0.72        60
weighted avg       0.82      0.83      0.82        60



# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
RandomForest(path_train,path_test)

[[54  5]
 [ 3 27]]
              precision    recall  f1-score   support

           0       0.92      0.95      0.93        57
           1       0.90      0.84      0.87        32

    accuracy                           0.91        89
   macro avg       0.91      0.90      0.90        89
weighted avg       0.91      0.91      0.91        89



# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
RandomForest(path_train,path_test)

[[ 0  1]
 [ 2 34]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.94      0.97      0.96        35

    accuracy                           0.92        37
   macro avg       0.47      0.49      0.48        37
weighted avg       0.89      0.92      0.91        37



# European

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
RandomForest(path_train,path_test)

[[53  6]
 [ 6 61]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        59
           1       0.91      0.91      0.91        67

    accuracy                           0.90       126
   macro avg       0.90      0.90      0.90       126
weighted avg       0.90      0.90      0.90       126



# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
RandomForest(path_train,path_test)

[[101  20]
 [ 21 134]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       122
           1       0.86      0.87      0.87       154

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276

