In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def RNN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(SimpleRNN(units=64, return_sequences=True, input_shape=(22, 1)))
    model.add(SimpleRNN(units=32, return_sequences=True))
    model.add(SimpleRNN(units=16))
    model.add(Dense(units=2, activation='sigmoid'))
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=10, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
RNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 3s 14ms/step - loss: 0.5629 - accuracy: 0.7170
Epoch 2/10
7/7 [==============================] - 0s 15ms/step - loss: 0.4261 - accuracy: 0.7925
Epoch 3/10
7/7 [==============================] - 0s 14ms/step - loss: 0.4139 - accuracy: 0.8113
Epoch 4/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3866 - accuracy: 0.8113
Epoch 5/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3643 - accuracy: 0.8255
Epoch 6/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3472 - accuracy: 0.8396
Epoch 7/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3332 - accuracy: 0.8585
Epoch 8/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3232 - accuracy: 0.8632
Epoch 9/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3219 - accuracy: 0.8538
Epoch 10/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3005 - accuracy: 0.8585
[[39  6]
 [12 34]]
          

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
RNN(path_train,path_test)

Epoch 1/10
5/5 [==============================] - 3s 17ms/step - loss: 0.5730 - accuracy: 0.7143
Epoch 2/10
5/5 [==============================] - 0s 19ms/step - loss: 0.5024 - accuracy: 0.7714
Epoch 3/10
5/5 [==============================] - 0s 18ms/step - loss: 0.4786 - accuracy: 0.7857
Epoch 4/10
5/5 [==============================] - 0s 17ms/step - loss: 0.4480 - accuracy: 0.7857
Epoch 5/10
5/5 [==============================] - 0s 20ms/step - loss: 0.4358 - accuracy: 0.8071
Epoch 6/10
5/5 [==============================] - 0s 19ms/step - loss: 0.4213 - accuracy: 0.8143
Epoch 7/10
5/5 [==============================] - 0s 19ms/step - loss: 0.4135 - accuracy: 0.8143
Epoch 8/10
5/5 [==============================] - 0s 18ms/step - loss: 0.3941 - accuracy: 0.8500
Epoch 9/10
5/5 [==============================] - 0s 18ms/step - loss: 0.3809 - accuracy: 0.8429
Epoch 10/10
5/5 [==============================] - 0s 29ms/step - loss: 0.3721 - accuracy: 0.8429
[[ 3  4]
 [10 43]]
          

# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
RNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 3s 16ms/step - loss: 0.5334 - accuracy: 0.7122
Epoch 2/10
7/7 [==============================] - 0s 17ms/step - loss: 0.3931 - accuracy: 0.8439
Epoch 3/10
7/7 [==============================] - 0s 20ms/step - loss: 0.3746 - accuracy: 0.8293
Epoch 4/10
7/7 [==============================] - 0s 19ms/step - loss: 0.3652 - accuracy: 0.8244
Epoch 5/10
7/7 [==============================] - 0s 17ms/step - loss: 0.3475 - accuracy: 0.8439
Epoch 6/10
7/7 [==============================] - 0s 18ms/step - loss: 0.3199 - accuracy: 0.8488
Epoch 7/10
7/7 [==============================] - 0s 16ms/step - loss: 0.3081 - accuracy: 0.8585
Epoch 8/10
7/7 [==============================] - 0s 16ms/step - loss: 0.3053 - accuracy: 0.8780
Epoch 9/10
7/7 [==============================] - 0s 16ms/step - loss: 0.2906 - accuracy: 0.8634
Epoch 10/10
7/7 [==============================] - 0s 15ms/step - loss: 0.2759 - accuracy: 0.8878
[[52  8]
 [ 5 24]]
          

# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
RNN(path_train,path_test)

Epoch 1/10
3/3 [==============================] - 3s 14ms/step - loss: 0.5461 - accuracy: 0.7558
Epoch 2/10
3/3 [==============================] - 0s 18ms/step - loss: 0.2569 - accuracy: 0.9302
Epoch 3/10
3/3 [==============================] - 0s 19ms/step - loss: 0.2330 - accuracy: 0.9302
Epoch 4/10
3/3 [==============================] - 0s 18ms/step - loss: 0.2046 - accuracy: 0.9302
Epoch 5/10
3/3 [==============================] - 0s 24ms/step - loss: 0.1839 - accuracy: 0.9302
Epoch 6/10
3/3 [==============================] - 0s 17ms/step - loss: 0.1582 - accuracy: 0.9302
Epoch 7/10
3/3 [==============================] - 0s 19ms/step - loss: 0.1485 - accuracy: 0.9535
Epoch 8/10
3/3 [==============================] - 0s 22ms/step - loss: 0.1431 - accuracy: 0.9535
Epoch 9/10
3/3 [==============================] - 0s 27ms/step - loss: 0.1336 - accuracy: 0.9651
Epoch 10/10
3/3 [==============================] - 0s 22ms/step - loss: 0.1263 - accuracy: 0.9651
[[ 0  1]
 [ 2 34]]
          

# Europe

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
RNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 3s 15ms/step - loss: 0.5980 - accuracy: 0.7113
Epoch 2/10
10/10 [==============================] - 0s 15ms/step - loss: 0.4302 - accuracy: 0.7869
Epoch 3/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3778 - accuracy: 0.8488
Epoch 4/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3509 - accuracy: 0.8488
Epoch 5/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3226 - accuracy: 0.8625
Epoch 6/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3073 - accuracy: 0.8660
Epoch 7/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3266 - accuracy: 0.8488
Epoch 8/10
10/10 [==============================] - 0s 16ms/step - loss: 0.3037 - accuracy: 0.8729
Epoch 9/10
10/10 [==============================] - 0s 16ms/step - loss: 0.3001 - accuracy: 0.8729
Epoch 10/10
10/10 [==============================] - 0s 15ms/step - loss: 0.2784 - accuracy: 0.8832
[[53 13]


# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
RNN(path_train,path_test)

Epoch 1/10
21/21 [==============================] - 3s 14ms/step - loss: 0.5311 - accuracy: 0.7407
Epoch 2/10
21/21 [==============================] - 0s 14ms/step - loss: 0.4347 - accuracy: 0.8012
Epoch 3/10
21/21 [==============================] - 0s 14ms/step - loss: 0.4052 - accuracy: 0.8183
Epoch 4/10
21/21 [==============================] - 0s 14ms/step - loss: 0.4009 - accuracy: 0.8245
Epoch 5/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3964 - accuracy: 0.8183
Epoch 6/10
21/21 [==============================] - 0s 15ms/step - loss: 0.3975 - accuracy: 0.8370
Epoch 7/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3878 - accuracy: 0.8416
Epoch 8/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3762 - accuracy: 0.8292
Epoch 9/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3783 - accuracy: 0.8339
Epoch 10/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3743 - accuracy: 0.8385
[[101  22

# Testing models on different data

In [9]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/euro_test.csv'
RNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 3s 16ms/step - loss: 0.5725 - accuracy: 0.7123
Epoch 2/10
7/7 [==============================] - 0s 18ms/step - loss: 0.4494 - accuracy: 0.8019
Epoch 3/10
7/7 [==============================] - 0s 17ms/step - loss: 0.4217 - accuracy: 0.7877
Epoch 4/10
7/7 [==============================] - 0s 17ms/step - loss: 0.3963 - accuracy: 0.8160
Epoch 5/10
7/7 [==============================] - 0s 17ms/step - loss: 0.3837 - accuracy: 0.8396
Epoch 6/10
7/7 [==============================] - 0s 18ms/step - loss: 0.3781 - accuracy: 0.8302
Epoch 7/10
7/7 [==============================] - 0s 18ms/step - loss: 0.3629 - accuracy: 0.8160
Epoch 8/10
7/7 [==============================] - 0s 18ms/step - loss: 0.3590 - accuracy: 0.8349
Epoch 9/10
7/7 [==============================] - 0s 16ms/step - loss: 0.3548 - accuracy: 0.8396
Epoch 10/10
7/7 [==============================] - 0s 16ms/step - loss: 0.3400 - accuracy: 0.8538
[[48  8]
 [11 59]]
          

In [10]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/cle_test.csv'
RNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 3s 14ms/step - loss: 0.5170 - accuracy: 0.7354
Epoch 2/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3781 - accuracy: 0.8351
Epoch 3/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3581 - accuracy: 0.8454
Epoch 4/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3423 - accuracy: 0.8625
Epoch 5/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3069 - accuracy: 0.8625
Epoch 6/10
10/10 [==============================] - 0s 16ms/step - loss: 0.3545 - accuracy: 0.8213
Epoch 7/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3432 - accuracy: 0.8419
Epoch 8/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3009 - accuracy: 0.8866
Epoch 9/10
10/10 [==============================] - 0s 14ms/step - loss: 0.2689 - accuracy: 0.8935
Epoch 10/10
10/10 [==============================] - 0s 16ms/step - loss: 0.2886 - accuracy: 0.8763
[[26  5]
