In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import preprocessing as sk_preprocessing

In [2]:
def svm(path_train,path_test):
    #load the train-test data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarylize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)
    
    #SVM
    svc = SVC()
    svc.fit(X_train, Y_train_binary.values.ravel())
    y_pred = svc.predict(X_test)
    print(confusion_matrix(Y_test_binary, y_pred))
    print(classification_report(Y_test_binary, y_pred))

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
svm(path_train,path_test)

[[43  8]
 [ 5 35]]
              precision    recall  f1-score   support

           0       0.90      0.84      0.87        51
           1       0.81      0.88      0.84        40

    accuracy                           0.86        91
   macro avg       0.85      0.86      0.86        91
weighted avg       0.86      0.86      0.86        91



# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
svm(path_train,path_test)

[[ 3 10]
 [ 1 46]]
              precision    recall  f1-score   support

           0       0.75      0.23      0.35        13
           1       0.82      0.98      0.89        47

    accuracy                           0.82        60
   macro avg       0.79      0.60      0.62        60
weighted avg       0.81      0.82      0.78        60



# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
svm(path_train,path_test)

[[53  4]
 [10 22]]
              precision    recall  f1-score   support

           0       0.84      0.93      0.88        57
           1       0.85      0.69      0.76        32

    accuracy                           0.84        89
   macro avg       0.84      0.81      0.82        89
weighted avg       0.84      0.84      0.84        89



# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
svm(path_train,path_test)

[[ 0  2]
 [ 0 35]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.95      1.00      0.97        35

    accuracy                           0.95        37
   macro avg       0.47      0.50      0.49        37
weighted avg       0.89      0.95      0.92        37



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# European

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
svm(path_train,path_test)

[[53  6]
 [10 57]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        59
           1       0.90      0.85      0.88        67

    accuracy                           0.87       126
   macro avg       0.87      0.87      0.87       126
weighted avg       0.88      0.87      0.87       126



# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
svm(path_train,path_test)

[[100  22]
 [ 18 136]]
              precision    recall  f1-score   support

           0       0.85      0.82      0.83       122
           1       0.86      0.88      0.87       154

    accuracy                           0.86       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.86      0.85       276

