In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN
from keras.layers import Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [3]:
cle = pd.read_csv('../TrainTestData/cle_metadata.csv')
vir = pd.read_csv('../TrainTestData/vir_metadata.csv')
hun = pd.read_csv('../TrainTestData/hun_metadata.csv')
swi = pd.read_csv('../TrainTestData/swi_metadata.csv')

In [4]:
data = pd.concat([cle,vir,hun,swi])
data

0    1    2         3         4    5         6    7         8  \
0    1.099659  0.0  0.0  0.872684  1.073222  0.0  1.486944  0.0  2.189892   
1    1.849904  0.0  0.0  0.620106  0.811350  0.0  1.943316  0.0  2.594235   
2    2.224025  0.0  0.0  0.119797  0.067982  0.0  2.657312  0.0  3.285271   
3    1.738161  0.0  0.0  0.520788  0.593032  0.0  2.272287  0.0  2.677983   
4    1.402882  0.0  0.0  0.570546  0.819004  0.0  1.494263  0.0  2.169592   
..        ...  ...  ...       ...       ...  ...       ...  ...       ...   
118  0.352982  0.0  0.0  1.839385  2.316214  0.0  0.474900  0.0  1.077897   
119  0.655624  0.0  0.0  1.390551  1.878792  0.0  0.452024  0.0  1.255075   
120  0.161753  0.0  0.0  1.826201  2.245803  0.0  0.137622  0.0  0.954996   
121  0.102779  0.0  0.0  1.974692  2.487005  0.0  0.091805  0.0  0.745667   
122  0.602246  0.0  0.0  1.550044  1.915930  0.0  0.562886  0.0  1.203250   

       9  ...  7.3       8.3  9.3  10.3      11.3      12.3  13.3  14.3  \
0    0.0  ...  0.0  1.457568  0.0   0.0  0.589020  0.882712   0.0   0.0   
1    0.0  ...  0.0  1.488225  0.0   0.0  0.637975  0.901482   0.0   0.0   
2    0.0  ...  0.0  1.199812  0.0   0.0  0.546282  0.756742   0.0   0.0   
3    0.0  ...  0.0  1.394613  0.0   0.0  0.627924  0.883689   0.0   0.0   
4    0.0  ...  0.0  1.280468  0.0   0.0  0.586185  0.768512   0.0   0.0   
..   ...  ...  ...       ...  ...   ...       ...       ...   ...   ...   
118  0.0  ...  0.0  1.968976  0.0   0.0  0.851110  1.141455   0.0   0.0   
119  0.0  ...  0.0  1.707302  0.0   0.0  0.670807  1.002500   0.0   0.0   
120  0.0  ...  0.0  1.802060  0.0   0.0  0.740325  1.043203   0.0   0.0   
121  0.0  ...  0.0  1.693194  0.0   0.0  0.653663  1.047537   0.0   0.0   
122  0.0  ...  0.0  1.498982  0.0   0.0  0.513196  0.959969   0.0   0.0   

         15.3   num  
0    1.598649  0.00  
1    1.643992  0.00  
2    1.321362  0.00  
3    1.631824  0.00  
4    1.481180  0.00  
..        ...   ...  
118  2.026502  0.75  
119  1.859282  0.50  
120  1.887837  1.00  
121  1.765075  0.25  
122  1.646081  0.25  

[920 rows x 65 columns]

In [5]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

In [6]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(SimpleRNN(units=64, return_sequences=True, input_shape=(64, 1)))
model.add(SimpleRNN(units=32, return_sequences=True))
model.add(SimpleRNN(units=16))
model.add(Dense(units=2, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred))

Epoch 1/1000
20/20 [==============================] - 3s 22ms/step - loss: 0.4735 - accuracy: 0.7857
Epoch 2/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.3840 - accuracy: 0.8442
Epoch 3/1000
20/20 [==============================] - 0s 22ms/step - loss: 0.3917 - accuracy: 0.8442
Epoch 4/1000
20/20 [==============================] - 0s 20ms/step - loss: 0.3746 - accuracy: 0.8442
Epoch 5/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.3652 - accuracy: 0.8474
Epoch 6/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.3626 - accuracy: 0.8458
Epoch 7/1000
20/20 [==============================] - 0s 22ms/step - loss: 0.3552 - accuracy: 0.8555
Epoch 8/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.3695 - accuracy: 0.8490
Epoch 9/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.3596 - accuracy: 0.8555
Epoch 10/1000
20/20 [==============================] - 0s 21ms/step - loss: 0.4036 - accura

In [7]:
model.save('../Models/Meta_Only/Meta_RNN.h5')

# Test on Each Datasets

In [8]:
def Test(path_train,path_test):
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #model = tf.keras.models.load_model(model_name)

    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [9]:
path_train = '../TrainTestData/cle_metadata_train.csv'
path_test = '../TrainTestData/cle_metadata_test.csv'
Test(path_train,path_test)

3/3 [==============================] - 0s 10ms/step
[[38  7]
 [10 36]]
              precision    recall  f1-score   support

           0       0.84      0.79      0.82        48
           1       0.78      0.84      0.81        43

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.82      0.81      0.81        91



# Virginia

In [11]:
path_train = '../TrainTestData/vir_metadata_train.csv'
path_test = '../TrainTestData/vir_metadata_test.csv'
Test(path_train,path_test)

2/2 [==============================] - 0s 10ms/step
[[ 4  2]
 [11 43]]
              precision    recall  f1-score   support

           0       0.67      0.27      0.38        15
           1       0.80      0.96      0.87        45

    accuracy                           0.78        60
   macro avg       0.73      0.61      0.62        60
weighted avg       0.76      0.78      0.75        60



# Hungarian

In [13]:
path_train = '../TrainTestData/hun_metadata_train.csv'
path_test = '../TrainTestData/hun_metadata_test.csv'
Test(path_train,path_test)

3/3 [==============================] - 0s 11ms/step
[[46  2]
 [ 9 32]]
              precision    recall  f1-score   support

           0       0.96      0.84      0.89        55
           1       0.78      0.94      0.85        34

    accuracy                           0.88        89
   macro avg       0.87      0.89      0.87        89
weighted avg       0.89      0.88      0.88        89



# Switzerland

In [14]:
path_train = '../TrainTestData/swi_metadata_train.csv'
path_test = '../TrainTestData/swi_metadata_test.csv'
Test(path_train,path_test)

2/2 [==============================] - 0s 9ms/step
[[ 1  4]
 [ 2 30]]
              precision    recall  f1-score   support

           0       0.20      0.33      0.25         3
           1       0.94      0.88      0.91        34

    accuracy                           0.84        37
   macro avg       0.57      0.61      0.58        37
weighted avg       0.88      0.84      0.86        37

