In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf

# CNN metadata:

In [21]:
cle = pd.read_csv('BaseMetaData/cle_metadata_cnn.csv')
vir = pd.read_csv('BaseMetaData/vir_metadata_cnn.csv')
hun = pd.read_csv('BaseMetaData/hun_metadata_cnn.csv')
swi = pd.read_csv('BaseMetaData/swi_metadata_cnn.csv')

In [22]:
cle_train,cle_test = train_test_split(cle,test_size=0.33, random_state=42)
vir_train,vir_test = train_test_split(vir,test_size=0.33, random_state=42)
hun_train,hun_test = train_test_split(hun,test_size=0.33, random_state=42)
swi_train,swi_test = train_test_split(swi,test_size=0.33, random_state=42)

In [23]:
cle_train.to_csv('SplitedMetaData/cle_metadata_cnn_train.csv',index = False)
cle_test.to_csv('SplitedMetaData/cle_metadata_cnn_test.csv',index = False)

In [24]:
vir_train.to_csv('SplitedMetaData/vir_metadata_cnn_train.csv',index = False)
vir_test.to_csv('SplitedMetaData/vir_metadata_cnn_test.csv',index = False)

In [25]:
hun_train.to_csv('SplitedMetaData/hun_metadata_cnn_train.csv',index = False)
hun_test.to_csv('SplitedMetaData/hun_metadata_cnn_test.csv',index = False)

In [26]:
swi_train.to_csv('SplitedMetaData/swi_metadata_cnn_train.csv',index = False)
swi_test.to_csv('SplitedMetaData/swi_metadata_cnn_test.csv',index = False)

In [115]:
cle_train=pd.read_csv('Archive/cle_metadata_cnn_train.csv')
cle_test=pd.read_csv('Archive/cle_metadata_cnn_test.csv' )

In [116]:
vir_train=pd.read_csv('Archive/vir_metadata_cnn_train.csv' )
vir_test=pd.read_csv('Archive/vir_metadata_cnn_test.csv' )

In [117]:
hun_train=pd.read_csv('Archive/hun_metadata_cnn_train.csv' )
hun_test=pd.read_csv('Archive/hun_metadata_cnn_test.csv' )

In [118]:
swi_train=pd.read_csv('Archive/swi_metadata_cnn_train.csv' )
swi_test=pd.read_csv('Archive/swi_metadata_cnn_test.csv' )

In [119]:
Train = pd.concat([cle_train,vir_train,hun_train])
Test = pd.concat([cle_test,vir_test,hun_test,swi_test,swi_train])

In [120]:
X_train = Train.iloc[:,:-1]
X_test = Test.iloc[:,:-1]

y_train = Train.iloc[:,-1]
y_test = Test.iloc[:,-1]

Y_train_binary = y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = y_test.apply(lambda x: 1 if x > 0 else 0)

In [121]:
X_train = X_train.iloc[:,:-16]
X_train

0         1         2         3         4         5         6  \
0    0.0  2.248868  0.031966  0.000000  0.084931  0.027487  1.848607   
1    0.0  1.431419  0.549506  0.177540  0.514307  0.604842  1.118270   
2    0.0  0.635330  1.127964  0.663026  0.960354  1.166600  0.497467   
3    0.0  2.256941  0.000000  0.000000  0.000000  0.000000  1.831003   
4    0.0  1.849345  0.338811  0.000000  0.213237  0.424558  1.518912   
..   ...       ...       ...       ...       ...       ...       ...   
191  0.0  0.911371  0.513962  0.040647  0.212746  0.558387  0.623158   
192  0.0  1.027598  0.422492  0.000000  0.169050  0.475569  0.700258   
193  0.0  0.411007  0.782775  0.347049  0.488997  0.778541  0.312183   
194  0.0  0.314719  0.847439  0.590235  0.633273  1.021742  0.326783   
195  0.0  0.916041  0.946292  0.374512  0.752015  0.958136  0.728709   

            7         8    9  ...  6.2       7.2  8.2  9.2  10.2  11.2  12.2  \
0    0.000000  0.000000  0.0  ...  0.0  0.458321  0.0  0.0   0.0   0.0   0.0   
1    0.155366  0.400950  0.0  ...  0.0  1.108881  0.0  0.0   0.0   0.0   0.0   
2    0.660284  1.020273  0.0  ...  0.0  2.274957  0.0  0.0   0.0   0.0   0.0   
3    0.000000  0.000000  0.0  ...  0.0  1.058112  0.0  0.0   0.0   0.0   0.0   
4    0.102218  0.287279  0.0  ...  0.0  1.246813  0.0  0.0   0.0   0.0   0.0   
..        ...       ...  ...  ...  ...       ...  ...  ...   ...   ...   ...   
191  0.154747  0.212299  0.0  ...  0.0  1.787779  0.0  0.0   0.0   0.0   0.0   
192  0.000000  0.054218  0.0  ...  0.0  1.019736  0.0  0.0   0.0   0.0   0.0   
193  0.473552  0.620706  0.0  ...  0.0  2.192840  0.0  0.0   0.0   0.0   0.0   
194  0.596144  0.912090  0.0  ...  0.0  1.596059  0.0  0.0   0.0   0.0   0.0   
195  0.355389  0.588221  0.0  ...  0.0  0.364294  0.0  0.0   0.0   0.0   0.0   

         13.2  14.2      15.2  
0    0.327989   0.0  1.113567  
1    0.652945   0.0  1.620916  
2    1.418039   0.0  3.057440  
3    0.647171   0.0  1.749359  
4    0.808062   0.0  2.168874  
..        ...   ...       ...  
191  1.155002   0.0  2.371952  
192  0.640007   0.0  1.325212  
193  1.553317   0.0  3.230714  
194  1.210355   0.0  2.520030  
195  0.168329   0.0  1.096703  

[533 rows x 48 columns]

In [122]:
X_test = X_test.iloc[:,:-16]
X_test

0         1         2         3         4         5         6         7  \
0   0.0  1.576204  0.425418  0.000000  0.268724  0.449675  1.255515  0.017467   
1   0.0  2.096074  0.112876  0.000000  0.143072  0.053330  1.652721  0.000000   
2   0.0  0.410527  1.482395  1.029471  1.204768  1.621189  0.422033  1.139812   
3   0.0  2.235174  0.074740  0.000000  0.079568  0.072115  1.834668  0.000000   
4   0.0  0.243156  1.304830  0.914779  1.077529  1.312706  0.370080  0.972016   
..  ...       ...       ...       ...       ...       ...       ...       ...   
77  0.0  2.161178  0.000000  0.000000  0.000000  0.000000  1.739848  0.000000   
78  0.0  1.258408  0.550577  0.167127  0.385352  0.657832  0.890879  0.085123   
79  0.0  1.513029  0.000000  0.000000  0.005490  0.000000  1.320644  0.000000   
80  0.0  1.742145  0.349108  0.000000  0.337999  0.408991  1.426055  0.000000   
81  0.0  2.415703  0.000000  0.000000  0.000000  0.000000  1.917221  0.000000   

           8    9  ...  6.2       7.2  8.2  9.2  10.2  11.2  12.2      13.2  \
0   0.127063  0.0  ...  0.0  1.399341  0.0  0.0   0.0   0.0   0.0  0.503240   
1   0.000000  0.0  ...  0.0  0.000000  0.0  0.0   0.0   0.0   0.0  0.000000   
2   1.480421  0.0  ...  0.0  2.289236  0.0  0.0   0.0   0.0   0.0  1.418965   
3   0.000000  0.0  ...  0.0  0.355788  0.0  0.0   0.0   0.0   0.0  0.271699   
4   1.398930  0.0  ...  0.0  1.782764  0.0  0.0   0.0   0.0   0.0  0.986294   
..       ...  ...  ...  ...       ...  ...  ...   ...   ...   ...       ...   
77  0.000000  0.0  ...  0.0  0.000000  0.0  0.0   0.0   0.0   0.0  0.000000   
78  0.314842  0.0  ...  0.0  1.044203  0.0  0.0   0.0   0.0   0.0  0.700594   
79  0.000000  0.0  ...  0.0  0.921914  0.0  0.0   0.0   0.0   0.0  0.715816   
80  0.000000  0.0  ...  0.0  0.000000  0.0  0.0   0.0   0.0   0.0  0.000000   
81  0.000000  0.0  ...  0.0  0.000000  0.0  0.0   0.0   0.0   0.0  0.000000   

    14.2      15.2  
0    0.0  2.327298  
1    0.0  0.000000  
2    0.0  3.460618  
3    0.0  1.012708  
4    0.0  2.950225  
..   ...       ...  
77   0.0  0.014986  
78   0.0  1.601484  
79   0.0  1.834675  
80   0.0  0.518541  
81   0.0  0.000000  

[387 rows x 48 columns]

In [123]:
cle_train_temp = cle_train.iloc[:,:-17]
cle_train_Y = cle_train.iloc[:,-1]
cle_train = pd.concat([cle_train_temp, cle_train_Y], axis=1)
cle_train.to_csv('cle_metadata_cnn_train.csv', index=False)

In [124]:
vir_train_temp = vir_train.iloc[:,:-17]
vir_train_Y = vir_train.iloc[:,-1]
vir_train = pd.concat([vir_train_temp, vir_train_Y], axis=1)
vir_train.to_csv('vir_metadata_cnn_train.csv', index=False)

In [125]:
hun_train_temp = hun_train.iloc[:,:-17]
hun_train_Y = hun_train.iloc[:,-1]
hun_train = pd.concat([hun_train_temp, hun_train_Y], axis=1)
hun_train.to_csv('hun_metadata_cnn_train.csv', index=False)

In [126]:
cle_test_temp = cle_test.iloc[:,:-17]
cle_test_Y = cle_test.iloc[:,-1]
cle_test = pd.concat([cle_test_temp, cle_test_Y], axis=1)
cle_test.to_csv('cle_metadata_cnn_test.csv', index=False)

In [127]:
vir_test_temp = vir_test.iloc[:,:-17]
vir_test_Y = vir_test.iloc[:,-1]
vir_test = pd.concat([vir_test_temp, vir_test_Y], axis=1)
vir_test.to_csv('vir_metadata_cnn_test.csv', index=False)

In [128]:
hun_test_temp = hun_test.iloc[:,:-17]
hun_test_Y = hun_test.iloc[:,-1]
hun_test = pd.concat([hun_test_temp, hun_test_Y], axis=1)
hun_test.to_csv('hun_metadata_cnn_test.csv', index=False)

In [130]:
# function for deep learning testing
def Test(path_train,path_test,model_name):
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]
    
    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    model = tf.keras.models.load_model(model_name)

    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))
    
    mismatch = [i for i, (a,b) in enumerate(zip(Y_pred, Y_test_binary)) if a != b]
    print(mismatch)

# CNN

In [38]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(48,1)))
model.add(Conv1D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 2s 47ms/step - loss: 0.4956 - accuracy: 0.7701
Epoch 2/1000
18/18 [==============================] - 1s 46ms/step - loss: 0.4446 - accuracy: 0.8285
Epoch 3/1000
18/18 [==============================] - 1s 48ms/step - loss: 0.4311 - accuracy: 0.8339
Epoch 4/1000
18/18 [==============================] - 1s 46ms/step - loss: 0.4113 - accuracy: 0.8358
Epoch 5/1000
18/18 [==============================] - 1s 47ms/step - loss: 0.3981 - accuracy: 0.8485
Epoch 6/1000
18/18 [==============================] - 1s 48ms/step - loss: 0.4024 - accuracy: 0.8285
Epoch 7/1000
18/18 [==============================] - 1s 44ms/step - loss: 0.4025 - accuracy: 0.8376
Epoch 8/1000
18/18 [==============================] - 1s 45ms/step - loss: 0.4020 - accuracy: 0.8412
Epoch 9/1000
18/18 [==============================] - 1s 44ms/step - loss: 0.3990 - accuracy: 0.8467
Epoch 10/1000
18/18 [==============================] - 1s 44ms/step - loss: 0.3860 - accura

In [39]:
model.save('../Models/Meta_Only/CNNMeta_CNN_test.h5')

# Test on each dataset

In [131]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

Cle test
4/4 [==============================] - 0s 10ms/step
[[37  5]
 [15 43]]
              precision    recall  f1-score   support

           0     0.8810    0.7115    0.7872        52
           1     0.7414    0.8958    0.8113        48

    accuracy                         0.8000       100
   macro avg     0.8112    0.8037    0.7993       100
weighted avg     0.8140    0.8000    0.7988       100

[9, 19, 22, 27, 28, 46, 48, 51, 53, 54, 62, 63, 66, 73, 74, 77, 81, 85, 86, 96]
vir test
3/3 [==============================] - 0s 8ms/step
[[ 5  2]
 [10 49]]
              precision    recall  f1-score   support

           0     0.7143    0.3333    0.4545        15
           1     0.8305    0.9608    0.8909        51

    accuracy                         0.8182        66
   macro avg     0.7724    0.6471    0.6727        66
weighted avg     0.8041    0.8182    0.7917        66

[6, 7, 8, 10, 19, 20, 23, 26, 35, 48, 57, 58]
hun test
4/4 [==============================] - 0s 11ms/step


ValueError: in user code:

    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\wangt\AppData\Roaming\Python\Python39\site-packages\keras\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 48, 1), found shape=(None, 64)


# DNN

In [41]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(Dense(64, input_shape=(48,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 1s 2ms/step - loss: 0.4764 - accuracy: 0.8120
Epoch 2/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4078 - accuracy: 0.8193
Epoch 3/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8157
Epoch 4/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4141 - accuracy: 0.8321
Epoch 5/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8321
Epoch 6/1000
18/18 [==============================] - 0s 3ms/step - loss: 0.4106 - accuracy: 0.8321
Epoch 7/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3984 - accuracy: 0.8303
Epoch 8/1000
18/18 [==============================] - 0s 3ms/step - loss: 0.3884 - accuracy: 0.8431
Epoch 9/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3953 - accuracy: 0.8394
Epoch 10/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.8321

In [15]:
model.save('../Models/Meta_Only/CNNMeta_DNN.h5')

# test on each dataset

In [16]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN.h5'
Test(path_train,path_test,model)

Cle test
[[39  5]
 [13 43]]
              precision    recall  f1-score   support

           0     0.8864    0.7500    0.8125        52
           1     0.7679    0.8958    0.8269        48

    accuracy                         0.8200       100
   macro avg     0.8271    0.8229    0.8197       100
weighted avg     0.8295    0.8200    0.8194       100

[9, 19, 20, 22, 27, 28, 46, 48, 53, 54, 62, 63, 73, 74, 77, 81, 86, 96]
vir test
[[ 5  1]
 [10 50]]
              precision    recall  f1-score   support

           0     0.8333    0.3333    0.4762        15
           1     0.8333    0.9804    0.9009        51

    accuracy                         0.8333        66
   macro avg     0.8333    0.6569    0.6885        66
weighted avg     0.8333    0.8333    0.8044        66

[6, 7, 8, 10, 19, 20, 23, 26, 35, 48, 58]
hun test
[[50  2]
 [10 36]]
              precision    recall  f1-score   support

           0     0.9615    0.8333    0.8929        60
           1     0.7826    0.9474    0.

# RNN

In [43]:
from keras.layers import Dense, SimpleRNN

In [44]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(SimpleRNN(units=64, return_sequences=True, input_shape=(48, 1)))
model.add(SimpleRNN(units=32, return_sequences=True))
model.add(SimpleRNN(units=16))
model.add(Dense(units=2, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 3s 16ms/step - loss: 0.4795 - accuracy: 0.7828
Epoch 2/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4645 - accuracy: 0.8029
Epoch 3/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4267 - accuracy: 0.8175
Epoch 4/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4247 - accuracy: 0.8193
Epoch 5/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4401 - accuracy: 0.8175
Epoch 6/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4176 - accuracy: 0.8266
Epoch 7/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4078 - accuracy: 0.8303
Epoch 8/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4427 - accuracy: 0.8011
Epoch 9/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4159 - accuracy: 0.8285
Epoch 10/1000
18/18 [==============================] - 0s 15ms/step - loss: 0.4096 - accura

In [19]:
model.save('../Models/Meta_Only/CNNMeta_RNN.h5')

In [20]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN.h5'
Test(path_train,path_test,model)

Cle test
[[35  5]
 [17 43]]
              precision    recall  f1-score   support

           0     0.8750    0.6731    0.7609        52
           1     0.7167    0.8958    0.7963        48

    accuracy                         0.7800       100
   macro avg     0.7958    0.7845    0.7786       100
weighted avg     0.7990    0.7800    0.7779       100

[9, 19, 20, 22, 27, 28, 38, 39, 46, 48, 53, 54, 62, 63, 66, 73, 74, 77, 81, 85, 86, 96]
vir test
[[ 3  1]
 [12 50]]
              precision    recall  f1-score   support

           0     0.7500    0.2000    0.3158        15
           1     0.8065    0.9804    0.8850        51

    accuracy                         0.8030        66
   macro avg     0.7782    0.5902    0.6004        66
weighted avg     0.7936    0.8030    0.7556        66

[6, 7, 8, 10, 19, 20, 23, 26, 35, 41, 48, 53, 58]
hun test
[[44  2]
 [16 36]]
              precision    recall  f1-score   support

           0     0.9565    0.7333    0.8302        60
           1   

# Machine Learning

# Decision Tree

In [45]:
from sklearn import tree
import matplotlib.pyplot as plt

In [47]:
# decision tree
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train, Y_train_binary)
Y_predictions = clf.predict(X_test)
cm = confusion_matrix(Y_predictions, Y_test_binary)
print("Confusion Matrix is:")
print(cm)
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements
print("Accuracy is : " + str(accuracy(cm)))
    
print("Report")
print(classification_report(Y_test_binary, Y_predictions))
    


Confusion Matrix is:
[[ 88  46]
 [ 35 203]]
Accuracy is : 0.782258064516129
Report
              precision    recall  f1-score   support

           0       0.66      0.72      0.68       123
           1       0.85      0.82      0.83       249

    accuracy                           0.78       372
   macro avg       0.75      0.77      0.76       372
weighted avg       0.79      0.78      0.78       372



In [53]:
# save clf model
from joblib import dump, load
#dump(clf, '../Models/Meta_only/CNNMeta_dt.joblib')

In [56]:
# function for Decision tree, and random forest testing
def Test_DT(path_train,path_test,model_name):
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    model = load(model_name)

    Y_pred = model.predict(X_test)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))
    
    mismatch = [i for i, (a,b) in enumerate(zip(Y_pred, Y_test_binary)) if a != b]
    print(mismatch)

In [57]:
#test on each dataset for decision tree
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

Cle test


ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

# Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, Y_train_binary)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred,digits = 4))

[[101  15]
 [ 22 234]]
              precision    recall  f1-score   support

           0     0.8707    0.8211    0.8452       123
           1     0.9141    0.9398    0.9267       249

    accuracy                         0.9005       372
   macro avg     0.8924    0.8804    0.8860       372
weighted avg     0.8997    0.9005    0.8998       372



In [54]:
dump(classifier, '../Models/Meta_only/CNNMeta_rf_9005.joblib')

['../Models/Meta_only/CNNMeta_rf_9005.joblib']

In [55]:
#test on each dataset for Random Forest
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf.joblib'
Test_DT(path_train,path_test,model)

Cle test


NameError: name 'Test_DT' is not defined

# SVM

In [58]:
from sklearn.svm import SVC

In [60]:
svc = SVC()
svc.fit(X_train, Y_train_binary.values.ravel())
y_pred = svc.predict(X_test)
print(confusion_matrix(Y_test_binary, y_pred))
print(classification_report(Y_test_binary, y_pred, digits = 4))

[[100  23]
 [ 15 234]]
              precision    recall  f1-score   support

           0     0.8696    0.8130    0.8403       123
           1     0.9105    0.9398    0.9249       249

    accuracy                         0.8978       372
   macro avg     0.8900    0.8764    0.8826       372
weighted avg     0.8970    0.8978    0.8969       372



In [61]:
import joblib
joblib.dump(svc, "../Models/Meta_only/CNNMeta_svm_8978.pkl") 

['../Models/Meta_only/CNNMeta_svm_8978.pkl']

In [33]:
#test on each dataset for SVM
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm.pkl'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm.pkl'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm.pkl'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm.pkl'
Test_DT(path_train,path_test,model)

Cle test
[[41  5]
 [11 43]]
              precision    recall  f1-score   support

           0     0.8913    0.7885    0.8367        52
           1     0.7963    0.8958    0.8431        48

    accuracy                         0.8400       100
   macro avg     0.8438    0.8421    0.8399       100
weighted avg     0.8457    0.8400    0.8398       100

[9, 19, 22, 27, 28, 46, 53, 62, 63, 73, 74, 77, 81, 85, 86, 96]
vir test
[[ 4  2]
 [11 49]]
              precision    recall  f1-score   support

           0     0.6667    0.2667    0.3810        15
           1     0.8167    0.9608    0.8829        51

    accuracy                         0.8030        66
   macro avg     0.7417    0.6137    0.6319        66
weighted avg     0.7826    0.8030    0.7688        66

[4, 6, 7, 8, 10, 19, 20, 23, 26, 35, 48, 53, 58]
hun test
[[50  3]
 [10 35]]
              precision    recall  f1-score   support

           0     0.9434    0.8333    0.8850        60
           1     0.7778    0.9211    0.8

# Bayesian Classifier

In [63]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, Y_train_binary)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits = 4))

dump(clf, '../Models/Meta_only/CNNMeta_NB_new.joblib')

[[103  26]
 [ 20 223]]
              precision    recall  f1-score   support

           0     0.7984    0.8374    0.8175       123
           1     0.9177    0.8956    0.9065       249

    accuracy                         0.8763       372
   macro avg     0.8581    0.8665    0.8620       372
weighted avg     0.8783    0.8763    0.8771       372



['../Models/Meta_only/CNNMeta_NB_new.joblib']

In [35]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB.joblib'
Test_DT(path_train,path_test,model)

Cle test
[[41 11]
 [11 37]]
              precision    recall  f1-score   support

           0     0.7885    0.7885    0.7885        52
           1     0.7708    0.7708    0.7708        48

    accuracy                         0.7800       100
   macro avg     0.7796    0.7796    0.7796       100
weighted avg     0.7800    0.7800    0.7800       100

[0, 9, 16, 18, 19, 26, 28, 36, 46, 48, 53, 56, 63, 73, 74, 75, 77, 81, 85, 86, 93, 96]
vir test
[[ 7  8]
 [ 8 43]]
              precision    recall  f1-score   support

           0     0.4667    0.4667    0.4667        15
           1     0.8431    0.8431    0.8431        51

    accuracy                         0.7576        66
   macro avg     0.6549    0.6549    0.6549        66
weighted avg     0.7576    0.7576    0.7576        66

[6, 7, 8, 9, 10, 20, 23, 26, 30, 34, 41, 46, 47, 48, 52, 59]
hun test
[[49  8]
 [11 30]]
              precision    recall  f1-score   support

           0     0.8596    0.8167    0.8376        60
     