In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf

# CNN metadata:

In [2]:
cle_train=pd.read_csv('cle_metadata_rnn_train.csv')
cle_test=pd.read_csv('cle_metadata_rnn_test.csv' )

In [3]:
vir_train=pd.read_csv('vir_metadata_rnn_train.csv' )
vir_test=pd.read_csv('vir_metadata_rnn_test.csv' )

In [4]:
hun_train=pd.read_csv('hun_metadata_rnn_train.csv' )
hun_test=pd.read_csv('hun_metadata_rnn_test.csv' )

In [5]:
swi_train=pd.read_csv('swi_metadata_rnn_train.csv' )
swi_test=pd.read_csv('swi_metadata_rnn_test.csv' )

In [6]:
Train = pd.concat([cle_train,vir_train,hun_train])
Test = pd.concat([cle_test,vir_test,hun_test,swi_test,swi_train])

In [7]:
X_train = Train.iloc[:,:-1]
X_test = Test.iloc[:,:-1]

y_train = Train.iloc[:,-1]
y_test = Test.iloc[:,-1]

Y_train_binary = y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = y_test.apply(lambda x: 1 if x > 0 else 0)

In [8]:
X_train = X_train.iloc[:,:-16]
X_train

0         1         2         3         4         5         6  \
0    0.340760  0.487900  0.612871  0.436759  0.526660  0.479218  0.720962   
1    0.297737  0.609399  0.685022  0.390012  0.413881  0.412132  0.613540   
2    0.253104  0.615953  0.671807  0.511258  0.520002  0.410881  0.645860   
3    0.328991  0.574650  0.604049  0.358715  0.608555  0.461843  0.672255   
4    0.385332  0.618744  0.452088  0.463268  0.672097  0.432593  0.549330   
..        ...       ...       ...       ...       ...       ...       ...   
195  0.339409  0.558035  0.257953  0.318239  0.379783  0.598093  0.619935   
196  0.420442  0.481506  0.177521  0.492286  0.377492  0.679658  0.416711   
197  0.513070  0.497011  0.324947  0.677927  0.474300  0.674969  0.250162   
198  0.560600  0.523055  0.483911  0.692399  0.362762  0.507424  0.333098   
199  0.566970  0.502197  0.420686  0.619997  0.381977  0.508727  0.326801   

            7         8         9  ...       6.2       7.2       8.2  \
0    0.436540  0.407657  0.592391  ...  0.374927  0.368879  0.585520   
1    0.267853  0.557113  0.737520  ...  0.437792  0.361421  0.498104   
2    0.305135  0.581857  0.713344  ...  0.412748  0.412591  0.446045   
3    0.444438  0.533643  0.654812  ...  0.345829  0.315530  0.613956   
4    0.464415  0.654181  0.591616  ...  0.411836  0.370949  0.400231   
..        ...       ...       ...  ...       ...       ...       ...   
195  0.308391  0.388721  0.557802  ...  0.451080  0.463271  0.427888   
196  0.237822  0.333888  0.483541  ...  0.401163  0.467945  0.446788   
197  0.398171  0.487661  0.557615  ...  0.575916  0.523433  0.485088   
198  0.380661  0.311507  0.616838  ...  0.538191  0.544019  0.497151   
199  0.363952  0.429766  0.561933  ...  0.689632  0.547575  0.481885   

          9.2      10.2      11.2      12.2      13.2      14.2      15.2  
0    0.548301  0.521280  0.389572  0.324228  0.230953  0.491484  0.281527  
1    0.511952  0.553327  0.441596  0.387916  0.273499  0.425464  0.271027  
2    0.513884  0.555546  0.442008  0.467973  0.307008  0.493194  0.259648  
3    0.540895  0.522999  0.414430  0.274560  0.239929  0.433457  0.305221  
4    0.538693  0.491434  0.503750  0.302947  0.249541  0.433775  0.294660  
..        ...       ...       ...       ...       ...       ...       ...  
195  0.398204  0.578371  0.419423  0.489791  0.561335  0.307842  0.479495  
196  0.380411  0.584302  0.456640  0.449737  0.596066  0.226348  0.611213  
197  0.544598  0.463815  0.562527  0.391307  0.551289  0.209695  0.337740  
198  0.648589  0.422161  0.584743  0.459314  0.503090  0.232661  0.264214  
199  0.632070  0.263566  0.569576  0.383654  0.539597  0.278412  0.217632  

[548 rows x 48 columns]

In [9]:
X_test = X_test.iloc[:,:-16]
X_test

0         1         2         3         4         5         6  \
0   0.293729  0.627477  0.526115  0.438907  0.638679  0.428233  0.487701   
1   0.320054  0.519304  0.611243  0.427906  0.500610  0.447715  0.682454   
2   0.186162  0.670216  0.551800  0.481192  0.550654  0.343080  0.545997   
3   0.342631  0.540192  0.565230  0.378897  0.547730  0.470122  0.738252   
4   0.225800  0.658236  0.485795  0.469096  0.494993  0.306525  0.447890   
..       ...       ...       ...       ...       ...       ...       ...   
77  0.811979  0.528964  0.477257  0.721589  0.766146  0.594920  0.575080   
78  0.642327  0.631567  0.459703  0.564522  0.617820  0.553694  0.466363   
79  0.788072  0.553832  0.477969  0.666801  0.759219  0.636976  0.515849   
80  0.777790  0.527051  0.445324  0.664927  0.776204  0.635988  0.572343   
81  0.745860  0.631236  0.514625  0.734407  0.697883  0.571744  0.525459   

           7         8         9  ...       6.2       7.2       8.2       9.2  \
0   0.418628  0.632747  0.546150  ...  0.356309  0.409993  0.498881  0.522675   
1   0.379712  0.434606  0.661573  ...  0.387747  0.370770  0.546051  0.589093   
2   0.292986  0.577275  0.719382  ...  0.362506  0.472912  0.380852  0.423283   
3   0.393265  0.475793  0.566919  ...  0.337585  0.340781  0.601751  0.537776   
4   0.257140  0.544094  0.731443  ...  0.410208  0.505617  0.353265  0.493895   
..       ...       ...       ...  ...       ...       ...       ...       ...   
77  0.485718  0.607156  0.486673  ...  0.607945  0.282076  0.352502  0.306273   
78  0.545977  0.647660  0.529072  ...  0.607786  0.330605  0.321269  0.224711   
79  0.551768  0.662098  0.530938  ...  0.629856  0.338659  0.298441  0.327477   
80  0.569432  0.574139  0.506169  ...  0.542415  0.319269  0.271290  0.300264   
81  0.499531  0.664431  0.485709  ...  0.639217  0.300555  0.299842  0.282024   

        10.2      11.2      12.2      13.2      14.2      15.2  
0   0.564499  0.483933  0.358412  0.277381  0.447570  0.304200  
1   0.563025  0.416531  0.309537  0.244754  0.488107  0.302487  
2   0.526330  0.433946  0.373257  0.310308  0.377175  0.327444  
3   0.490526  0.401568  0.325775  0.229961  0.531719  0.251820  
4   0.559228  0.576092  0.491070  0.387742  0.303094  0.404555  
..       ...       ...       ...       ...       ...       ...  
77  0.248539  0.421206  0.445894  0.351136  0.698048  0.548143  
78  0.391932  0.318150  0.571609  0.298220  0.666262  0.645772  
79  0.207824  0.461076  0.476232  0.470051  0.728933  0.506881  
80  0.314978  0.487840  0.478168  0.385513  0.620938  0.578300  
81  0.230102  0.403596  0.475483  0.442517  0.704997  0.554428  

[372 rows x 48 columns]

In [10]:
cle_train_temp = cle_train.iloc[:,:-17]
cle_train_Y = cle_train.iloc[:,-1]
cle_train = pd.concat([cle_train_temp, cle_train_Y], axis=1)
cle_train.to_csv('cle_metadata_rnn_train.csv', index=False)

In [11]:
vir_train_temp = vir_train.iloc[:,:-17]
vir_train_Y = vir_train.iloc[:,-1]
vir_train = pd.concat([vir_train_temp, vir_train_Y], axis=1)
vir_train.to_csv('vir_metadata_rnn_train.csv', index=False)

In [12]:
hun_train_temp = hun_train.iloc[:,:-17]
hun_train_Y = hun_train.iloc[:,-1]
hun_train = pd.concat([hun_train_temp, hun_train_Y], axis=1)
hun_train.to_csv('hun_metadata_rnn_train.csv', index=False)

In [13]:
cle_test_temp = cle_test.iloc[:,:-17]
cle_test_Y = cle_test.iloc[:,-1]
cle_test = pd.concat([cle_test_temp, cle_test_Y], axis=1)
cle_test.to_csv('cle_metadata_rnn_test.csv', index=False)

In [14]:
vir_test_temp = vir_test.iloc[:,:-17]
vir_test_Y = vir_test.iloc[:,-1]
vir_test = pd.concat([vir_test_temp, vir_test_Y], axis=1)
vir_test.to_csv('vir_metadata_rnn_test.csv', index=False)

In [15]:
hun_test_temp = hun_test.iloc[:,:-17]
hun_test_Y = hun_test.iloc[:,-1]
hun_test = pd.concat([hun_test_temp, hun_test_Y], axis=1)
hun_test.to_csv('hun_metadata_rnn_test.csv', index=False)

In [16]:
swi_test_new = pd.concat([swi_train, swi_test])
swi_test_new 

0         1         2         3         4         5         6  \
0   0.843553  0.625444  0.555617  0.760166  0.765526  0.596982  0.530243   
1   0.859244  0.567619  0.547963  0.713528  0.747644  0.608982  0.519941   
2   0.780039  0.697458  0.389511  0.597518  0.771891  0.571629  0.488341   
3   0.713523  0.607888  0.483635  0.694529  0.806823  0.612920  0.660157   
4   0.850672  0.522852  0.504845  0.707535  0.770107  0.603788  0.553652   
..       ...       ...       ...       ...       ...       ...       ...   
36  0.744582  0.536951  0.559382  0.815555  0.734042  0.535882  0.612130   
37  0.832064  0.514286  0.526122  0.714009  0.752858  0.577719  0.559788   
38  0.786386  0.570039  0.496775  0.754366  0.731581  0.588903  0.531405   
39  0.810553  0.613983  0.499748  0.645507  0.731505  0.617283  0.499459   
40  0.628722  0.657938  0.356865  0.584840  0.725283  0.521924  0.559803   

           7         8         9  ...       7.3       8.3       9.3      10.3  \
0   0.402120  0.651977  0.514481  ...  0.335399  0.423963  0.414680  0.411113   
1   0.431107  0.577883  0.488516  ...  0.348661  0.562291  0.436564  0.310992   
2   0.486743  0.583345  0.527227  ...  0.475333  0.490168  0.445705  0.661218   
3   0.640414  0.640178  0.572145  ...  0.475699  0.624069  0.442532  0.440203   
4   0.456883  0.595856  0.495372  ...  0.496580  0.552390  0.502629  0.433395   
..       ...       ...       ...  ...       ...       ...       ...       ...   
36  0.526636  0.729768  0.497337  ...  0.513009  0.608218  0.707544  0.544682   
37  0.471312  0.605351  0.481386  ...  0.501527  0.496052  0.501094  0.480891   
38  0.472208  0.693943  0.478677  ...  0.436863  0.540070  0.413623  0.435573   
39  0.488158  0.567542  0.502843  ...  0.306206  0.476674  0.564807  0.367314   
40  0.600596  0.615933  0.536472  ...  0.351643  0.654072  0.557189  0.447027   

        11.3      12.3      13.3      14.3      15.3   num  
0   0.356875  0.589239  0.453639  0.364173  0.671544  0.75  
1   0.336308  0.473487  0.448962  0.331380  0.644962  0.75  
2   0.534539  0.667475  0.329092  0.603276  0.497078  0.50  
3   0.509695  0.357667  0.390793  0.520910  0.665331  0.25  
4   0.426027  0.632972  0.384774  0.414650  0.560253  0.25  
..       ...       ...       ...       ...       ...   ...  
36  0.521964  0.579941  0.385669  0.648660  0.460335  0.25  
37  0.444719  0.616671  0.458290  0.388410  0.583274  0.25  
38  0.381316  0.574634  0.493015  0.369902  0.502731  0.75  
39  0.347459  0.593353  0.517851  0.250259  0.637445  0.25  
40  0.362921  0.506199  0.504778  0.406993  0.576834  0.75  

[123 rows x 65 columns]

In [17]:
swi_test_temp = swi_test_new.iloc[:,:-17]
swi_test_Y = swi_test_new.iloc[:,-1]
swi_test = pd.concat([swi_test_temp, swi_test_Y], axis=1)
swi_test.to_csv('swi_metadata_rnn_test.csv', index=False)

In [18]:
# function for deep learning testing
def Test(path_train,path_test,model_name):
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]
    
    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    model = tf.keras.models.load_model(model_name)

    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))
    
    mismatch = [i for i, (a,b) in enumerate(zip(Y_pred, Y_test_binary)) if a != b]
    print(mismatch)

# CNN

In [19]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(48,1)))
model.add(Conv1D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 2s 59ms/step - loss: 0.6965 - accuracy: 0.5146
Epoch 2/1000
18/18 [==============================] - 1s 56ms/step - loss: 0.6585 - accuracy: 0.6131
Epoch 3/1000
18/18 [==============================] - 1s 56ms/step - loss: 0.5267 - accuracy: 0.7372
Epoch 4/1000
18/18 [==============================] - 1s 58ms/step - loss: 0.4973 - accuracy: 0.7737
Epoch 5/1000
18/18 [==============================] - 1s 56ms/step - loss: 0.4708 - accuracy: 0.7974
Epoch 6/1000
18/18 [==============================] - 1s 56ms/step - loss: 0.4379 - accuracy: 0.7993
Epoch 7/1000
18/18 [==============================] - 1s 59ms/step - loss: 0.4211 - accuracy: 0.8029
Epoch 8/1000
18/18 [==============================] - 1s 62ms/step - loss: 0.4233 - accuracy: 0.8175
Epoch 9/1000
18/18 [==============================] - 1s 62ms/step - loss: 0.4310 - accuracy: 0.8047
Epoch 10/1000
18/18 [==============================] - 1s 61ms/step - loss: 0.3882 - accura

In [39]:
model.save('../Models/Meta_Only/RNNMeta_CNN_test.h5')

# Test on each dataset

In [42]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/RNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/RNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/RNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/RNNMeta_CNN_test.h5'
Test(path_train,path_test,model)

Cle test
3/3 [==============================] - 0s 12ms/step
[[37  4]
 [ 9 43]]
              precision    recall  f1-score   support

           0     0.9024    0.8043    0.8506        46
           1     0.8269    0.9149    0.8687        47

    accuracy                         0.8602        93
   macro avg     0.8647    0.8596    0.8596        93
weighted avg     0.8643    0.8602    0.8597        93

[18, 25, 44, 47, 49, 50, 58, 59, 62, 69, 72, 79, 89]
vir test
2/2 [==============================] - 0s 13ms/step
[[ 5  2]
 [ 6 49]]
              precision    recall  f1-score   support

           0     0.7143    0.4545    0.5556        11
           1     0.8909    0.9608    0.9245        51

    accuracy                         0.8710        62
   macro avg     0.8026    0.7077    0.7400        62
weighted avg     0.8596    0.8710    0.8591        62

[6, 7, 17, 20, 23, 32, 53, 54]
hun test
3/3 [==============================] - 0s 13ms/step
[[50  1]
 [ 8 35]]
              precisio

# DNN

In [50]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(Dense(64, input_shape=(48,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 1s 2ms/step - loss: 0.5007 - accuracy: 0.7847
Epoch 2/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 0.8394
Epoch 3/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8431
Epoch 4/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3976 - accuracy: 0.8467
Epoch 5/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8431
Epoch 6/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3865 - accuracy: 0.8449
Epoch 7/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3830 - accuracy: 0.8358
Epoch 8/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8449
Epoch 9/1000
18/18 [==============================] - 0s 2ms/step - loss: 0.3884 - accuracy: 0.8358
Epoch 10/1000
18/18 [==============================] - 0s 3ms/step - loss: 0.3838 - accuracy: 0.8467

In [51]:
model.save('../Models/Meta_Only/CNNMeta_DNN_dropswi.h5')

# test on each dataset

In [52]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_DNN_dropswi.h5'
Test(path_train,path_test,model)

Cle test
3/3 [==============================] - 0s 2ms/step
[[44  5]
 [ 2 42]]
              precision    recall  f1-score   support

           0     0.8980    0.9565    0.9263        46
           1     0.9545    0.8936    0.9231        47

    accuracy                         0.9247        93
   macro avg     0.9263    0.9251    0.9247        93
weighted avg     0.9266    0.9247    0.9247        93

[17, 18, 58, 59, 69, 72, 89]
vir test
2/2 [==============================] - 0s 3ms/step
[[ 4  1]
 [ 7 50]]
              precision    recall  f1-score   support

           0     0.8000    0.3636    0.5000        11
           1     0.8772    0.9804    0.9259        51

    accuracy                         0.8710        62
   macro avg     0.8386    0.6720    0.7130        62
weighted avg     0.8635    0.8710    0.8504        62

[6, 7, 17, 20, 23, 32, 49, 54]
hun test
3/3 [==============================] - 0s 2ms/step
[[51  0]
 [ 7 36]]
              precision    recall  f1-score   sup

# RNN

In [53]:
from keras.layers import Dense, SimpleRNN

In [54]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5)

# define the model architecture
model = Sequential()
model.add(SimpleRNN(units=64, return_sequences=True, input_shape=(48, 1)))
model.add(SimpleRNN(units=32, return_sequences=True))
model.add(SimpleRNN(units=16))
model.add(Dense(units=2, activation='sigmoid'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
model.fit(X_train, Y_train_binary, epochs=1000, batch_size=32,callbacks=[callback])
Y_pred = model.predict(X_test).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits=4))

Epoch 1/1000
18/18 [==============================] - 3s 18ms/step - loss: 0.5653 - accuracy: 0.7427
Epoch 2/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4559 - accuracy: 0.7865
Epoch 3/1000
18/18 [==============================] - 0s 17ms/step - loss: 0.4227 - accuracy: 0.8084
Epoch 4/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4078 - accuracy: 0.8321
Epoch 5/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4139 - accuracy: 0.8212
Epoch 6/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4093 - accuracy: 0.8303
Epoch 7/1000
18/18 [==============================] - 0s 17ms/step - loss: 0.4026 - accuracy: 0.8321
Epoch 8/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4044 - accuracy: 0.8339
Epoch 9/1000
18/18 [==============================] - 0s 16ms/step - loss: 0.4372 - accuracy: 0.8157
Epoch 10/1000
18/18 [==============================] - 0s 17ms/step - loss: 0.4142 - accura

In [55]:
model.save('../Models/Meta_Only/CNNMeta_RNN_dropswi.h5')

In [56]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN_dropswi.h5'
Test(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_Only/CNNMeta_RNN_dropswi.h5'
Test(path_train,path_test,model)

Cle test
3/3 [==============================] - 0s 9ms/step
[[40  5]
 [ 6 42]]
              precision    recall  f1-score   support

           0     0.8889    0.8696    0.8791        46
           1     0.8750    0.8936    0.8842        47

    accuracy                         0.8817        93
   macro avg     0.8819    0.8816    0.8817        93
weighted avg     0.8819    0.8817    0.8817        93

[0, 19, 25, 44, 49, 58, 59, 69, 72, 79, 89]
vir test
2/2 [==============================] - 0s 9ms/step
[[ 7  3]
 [ 4 48]]
              precision    recall  f1-score   support

           0     0.7000    0.6364    0.6667        11
           1     0.9231    0.9412    0.9320        51

    accuracy                         0.8871        62
   macro avg     0.8115    0.7888    0.7994        62
weighted avg     0.8835    0.8871    0.8850        62

[6, 7, 17, 20, 23, 25, 53]
hun test
3/3 [==============================] - 0s 8ms/step
[[51  0]
 [ 7 36]]
              precision    recall  f1-

# Machine Learning

# Decision Tree

In [57]:
from sklearn import tree
import matplotlib.pyplot as plt

In [58]:
# decision tree
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train, Y_train_binary)
Y_predictions = clf.predict(X_test)
cm = confusion_matrix(Y_predictions, Y_test_binary)
print("Confusion Matrix is:")
print(cm)
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements
print("Accuracy is : " + str(accuracy(cm)))
    
print("Report")
print(classification_report(Y_test_binary, Y_predictions))
    


Confusion Matrix is:
[[ 88  54]
 [ 35 195]]
Accuracy is : 0.760752688172043
Report
              precision    recall  f1-score   support

           0       0.62      0.72      0.66       123
           1       0.85      0.78      0.81       249

    accuracy                           0.76       372
   macro avg       0.73      0.75      0.74       372
weighted avg       0.77      0.76      0.76       372



In [64]:
# save clf model
from joblib import dump, load
dump(clf, '../Models/Meta_only/CNNMeta_dt.joblib')

['../Models/Meta_only/CNNMeta_dt.joblib']

In [65]:
# function for Decision tree, and random forest testing
def Test_DT(path_train,path_test,model_name):
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    model = load(model_name)

    Y_pred = model.predict(X_test)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))
    
    mismatch = [i for i, (a,b) in enumerate(zip(Y_pred, Y_test_binary)) if a != b]
    print(mismatch)

In [66]:
#test on each dataset for decision tree
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_dt.joblib'
Test_DT(path_train,path_test,model)

Cle test
[[38 13]
 [ 8 34]]
              precision    recall  f1-score   support

           0     0.7451    0.8261    0.7835        46
           1     0.8095    0.7234    0.7640        47

    accuracy                         0.7742        93
   macro avg     0.7773    0.7747    0.7738        93
weighted avg     0.7777    0.7742    0.7737        93

[4, 9, 15, 17, 19, 22, 25, 33, 34, 38, 41, 44, 47, 52, 59, 69, 70, 72, 76, 78, 89]
vir test
[[ 7  5]
 [ 4 46]]
              precision    recall  f1-score   support

           0     0.5833    0.6364    0.6087        11
           1     0.9200    0.9020    0.9109        51

    accuracy                         0.8548        62
   macro avg     0.7517    0.7692    0.7598        62
weighted avg     0.8603    0.8548    0.8573        62

[4, 7, 17, 20, 31, 32, 53, 58, 60]
hun test
[[41  5]
 [17 31]]
              precision    recall  f1-score   support

           0     0.8913    0.7069    0.7885        58
           1     0.6458    0.8611  

# Random Forest

In [67]:
from sklearn.ensemble import RandomForestClassifier

In [68]:
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, Y_train_binary)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred,digits = 4))

[[101  15]
 [ 22 234]]
              precision    recall  f1-score   support

           0     0.8707    0.8211    0.8452       123
           1     0.9141    0.9398    0.9267       249

    accuracy                         0.9005       372
   macro avg     0.8924    0.8804    0.8860       372
weighted avg     0.8997    0.9005    0.8998       372



In [69]:
dump(classifier, '../Models/Meta_only/CNNMeta_rf_9005.joblib')

['../Models/Meta_only/CNNMeta_rf_9005.joblib']

In [72]:
#test on each dataset for Random Forest
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf_9005.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf_9005.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf_9005.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_rf_9005.joblib'
Test_DT(path_train,path_test,model)

Cle test
[[42  6]
 [ 4 41]]
              precision    recall  f1-score   support

           0     0.8750    0.9130    0.8936        46
           1     0.9111    0.8723    0.8913        47

    accuracy                         0.8925        93
   macro avg     0.8931    0.8927    0.8925        93
weighted avg     0.8932    0.8925    0.8924        93

[17, 18, 32, 49, 59, 69, 72, 76, 79, 89]
vir test
[[ 6  4]
 [ 5 47]]
              precision    recall  f1-score   support

           0     0.6000    0.5455    0.5714        11
           1     0.9038    0.9216    0.9126        51

    accuracy                         0.8548        62
   macro avg     0.7519    0.7335    0.7420        62
weighted avg     0.8499    0.8548    0.8521        62

[4, 6, 7, 17, 20, 23, 32, 39, 53]
hun test
[[50  2]
 [ 8 34]]
              precision    recall  f1-score   support

           0     0.9615    0.8621    0.9091        58
           1     0.8095    0.9444    0.8718        36

    accuracy           

# SVM

In [73]:
from sklearn.svm import SVC

In [74]:
svc = SVC()
svc.fit(X_train, Y_train_binary.values.ravel())
y_pred = svc.predict(X_test)
print(confusion_matrix(Y_test_binary, y_pred))
print(classification_report(Y_test_binary, y_pred, digits = 4))

[[100  23]
 [ 15 234]]
              precision    recall  f1-score   support

           0     0.8696    0.8130    0.8403       123
           1     0.9105    0.9398    0.9249       249

    accuracy                         0.8978       372
   macro avg     0.8900    0.8764    0.8826       372
weighted avg     0.8970    0.8978    0.8969       372



In [75]:
import joblib
joblib.dump(svc, "../Models/Meta_only/CNNMeta_svm_8978.pkl") 

['../Models/Meta_only/CNNMeta_svm_8978.pkl']

In [76]:
#test on each dataset for SVM
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm_8978.pkl'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm_8978.pkl'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm_8978.pkl'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_svm_8978.pkl'
Test_DT(path_train,path_test,model)

Cle test
[[41  4]
 [ 5 43]]
              precision    recall  f1-score   support

           0     0.9111    0.8913    0.9011        46
           1     0.8958    0.9149    0.9053        47

    accuracy                         0.9032        93
   macro avg     0.9035    0.9031    0.9032        93
weighted avg     0.9034    0.9032    0.9032        93

[18, 25, 49, 58, 59, 69, 72, 79, 89]
vir test
[[ 5  2]
 [ 6 49]]
              precision    recall  f1-score   support

           0     0.7143    0.4545    0.5556        11
           1     0.8909    0.9608    0.9245        51

    accuracy                         0.8710        62
   macro avg     0.8026    0.7077    0.7400        62
weighted avg     0.8596    0.8710    0.8591        62

[4, 6, 7, 17, 20, 23, 32, 54]
hun test
[[51  1]
 [ 7 35]]
              precision    recall  f1-score   support

           0     0.9808    0.8793    0.9273        58
           1     0.8333    0.9722    0.8974        36

    accuracy                   

# Bayesian Classifier

In [78]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, Y_train_binary)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_pred, Y_test_binary)
print(cm)
print(classification_report(Y_test_binary, Y_pred, digits = 4))

dump(clf, '../Models/Meta_only/CNNMeta_NB_dropswi.joblib')

[[103  26]
 [ 20 223]]
              precision    recall  f1-score   support

           0     0.7984    0.8374    0.8175       123
           1     0.9177    0.8956    0.9065       249

    accuracy                         0.8763       372
   macro avg     0.8581    0.8665    0.8620       372
weighted avg     0.8783    0.8763    0.8771       372



['../Models/Meta_only/CNNMeta_NB_dropswi.joblib']

In [79]:
print("Cle test")
path_train = 'cle_metadata_cnn_train.csv'
path_test = 'cle_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB_dropswi.joblib'
Test_DT(path_train,path_test,model)

print("==================")

print("vir test")
path_train = 'vir_metadata_cnn_train.csv'
path_test = 'vir_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB_dropswi.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("hun test")
path_train = 'hun_metadata_cnn_train.csv'
path_test = 'hun_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB_dropswi.joblib'
Test_DT(path_train,path_test,model)

print("==================")
print("swi test")
path_train = 'swi_metadata_cnn_train.csv'
path_test = 'swi_metadata_cnn_test.csv'
model = '../Models/Meta_only/CNNMeta_NB_dropswi.joblib'
Test_DT(path_train,path_test,model)

Cle test
[[38 13]
 [ 8 34]]
              precision    recall  f1-score   support

           0     0.7451    0.8261    0.7835        46
           1     0.8095    0.7234    0.7640        47

    accuracy                         0.7742        93
   macro avg     0.7773    0.7747    0.7738        93
weighted avg     0.7777    0.7742    0.7737        93

[4, 9, 15, 17, 19, 22, 25, 33, 34, 38, 41, 44, 47, 52, 59, 69, 70, 72, 76, 78, 89]
vir test
[[ 7  5]
 [ 4 46]]
              precision    recall  f1-score   support

           0     0.5833    0.6364    0.6087        11
           1     0.9200    0.9020    0.9109        51

    accuracy                         0.8548        62
   macro avg     0.7517    0.7692    0.7598        62
weighted avg     0.8603    0.8548    0.8573        62

[4, 7, 17, 20, 31, 32, 53, 58, 60]
hun test
[[41  5]
 [17 31]]
              precision    recall  f1-score   support

           0     0.8913    0.7069    0.7885        58
           1     0.6458    0.8611  