In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def BayesianClassifier(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = GaussianNB()
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))

# Cleveland

In [3]:
path_train = '../cle_train.csv'
path_test = '../cle_test.csv'
BayesianClassifier(path_train,path_test)

[[44  5]
 [ 9 35]]
              precision    recall  f1-score   support

           0     0.8980    0.8302    0.8627        53
           1     0.7955    0.8750    0.8333        40

    accuracy                         0.8495        93
   macro avg     0.8467    0.8526    0.8480        93
weighted avg     0.8539    0.8495    0.8501        93



# Virginia

In [4]:
path_train = '../vir_train.csv'
path_test = '../vir_test.csv'
BayesianClassifier(path_train,path_test)

[[ 5  9]
 [15 33]]
              precision    recall  f1-score   support

           0     0.3571    0.2500    0.2941        20
           1     0.6875    0.7857    0.7333        42

    accuracy                         0.6129        62
   macro avg     0.5223    0.5179    0.5137        62
weighted avg     0.5809    0.6129    0.5917        62



# Hungary

In [5]:
path_train = '../hun_train.csv'
path_test = '../hun_test.csv'
BayesianClassifier(path_train,path_test)

[[36  2]
 [18 38]]
              precision    recall  f1-score   support

           0     0.9474    0.6667    0.7826        54
           1     0.6786    0.9500    0.7917        40

    accuracy                         0.7872        94
   macro avg     0.8130    0.8083    0.7871        94
weighted avg     0.8330    0.7872    0.7865        94



# Switzerland

In [6]:
path_train = '../swi_train.csv'
path_test = '../swi_test.csv'
BayesianClassifier(path_train,path_test)

[[ 2 24]
 [ 0 15]]
              precision    recall  f1-score   support

           0     0.0769    1.0000    0.1429         2
           1     1.0000    0.3846    0.5556        39

    accuracy                         0.4146        41
   macro avg     0.5385    0.6923    0.3492        41
weighted avg     0.9550    0.4146    0.5354        41



# Combined

In [7]:
path_train = '../com_train.csv'
path_test = '../com_test.csv'
BayesianClassifier(path_train,path_test)

[[ 98  23]
 [ 24 131]]
              precision    recall  f1-score   support

           0     0.8099    0.8033    0.8066       122
           1     0.8452    0.8506    0.8479       154

    accuracy                         0.8297       276
   macro avg     0.8275    0.8270    0.8272       276
weighted avg     0.8296    0.8297    0.8296       276

