In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def RandomForest(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = RandomForestClassifier(n_estimators=100, random_state=42)
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred, digits=4))

# Cleveland

In [3]:
path_train = '../cle_train.csv'
path_test = '../cle_test.csv'
RandomForest(path_train,path_test)

[[45  6]
 [ 8 34]]
              precision    recall  f1-score   support

           0     0.8824    0.8491    0.8654        53
           1     0.8095    0.8500    0.8293        40

    accuracy                         0.8495        93
   macro avg     0.8459    0.8495    0.8473        93
weighted avg     0.8510    0.8495    0.8499        93



# Virginia

In [4]:
path_train = '../vir_train.csv'
path_test = '../vir_test.csv'
RandomForest(path_train,path_test)

[[ 6  3]
 [14 39]]
              precision    recall  f1-score   support

           0     0.6667    0.3000    0.4138        20
           1     0.7358    0.9286    0.8211        42

    accuracy                         0.7258        62
   macro avg     0.7013    0.6143    0.6174        62
weighted avg     0.7135    0.7258    0.6897        62



# Hungary

In [5]:
path_train = '../hun_train.csv'
path_test = '../hun_test.csv'
RandomForest(path_train,path_test)

[[52  8]
 [ 2 32]]
              precision    recall  f1-score   support

           0     0.8667    0.9630    0.9123        54
           1     0.9412    0.8000    0.8649        40

    accuracy                         0.8936        94
   macro avg     0.9039    0.8815    0.8886        94
weighted avg     0.8984    0.8936    0.8921        94



# Switzerland

In [6]:
path_train = '../swi_train.csv'
path_test = '../swi_test.csv'
RandomForest(path_train,path_test)

[[ 0  0]
 [ 2 39]]
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9512    1.0000    0.9750        39

    accuracy                         0.9512        41
   macro avg     0.4756    0.5000    0.4875        41
weighted avg     0.9048    0.9512    0.9274        41



c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Combined

In [7]:
path_train = '../com_train.csv'
path_test = '../com_test.csv'
RandomForest(path_train,path_test)

[[101  20]
 [ 21 134]]
              precision    recall  f1-score   support

           0     0.8347    0.8279    0.8313       122
           1     0.8645    0.8701    0.8673       154

    accuracy                         0.8514       276
   macro avg     0.8496    0.8490    0.8493       276
weighted avg     0.8513    0.8514    0.8514       276

