In [8]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

In [11]:
def BayesianClassifier(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = GaussianNB()
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [12]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
BayesianClassifier(path_train,path_test)

[[47 12]
 [ 4 28]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.85        51
           1       0.88      0.70      0.78        40

    accuracy                           0.82        91
   macro avg       0.84      0.81      0.82        91
weighted avg       0.83      0.82      0.82        91



# Virginia

In [13]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
BayesianClassifier(path_train,path_test)

[[ 7  6]
 [ 6 41]]
              precision    recall  f1-score   support

           0       0.54      0.54      0.54        13
           1       0.87      0.87      0.87        47

    accuracy                           0.80        60
   macro avg       0.71      0.71      0.71        60
weighted avg       0.80      0.80      0.80        60



# European

In [16]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
BayesianClassifier(path_train,path_test)

[[52  8]
 [ 7 59]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.87        59
           1       0.89      0.88      0.89        67

    accuracy                           0.88       126
   macro avg       0.88      0.88      0.88       126
weighted avg       0.88      0.88      0.88       126



# Combined

In [17]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
BayesianClassifier(path_train,path_test)

[[ 98  23]
 [ 24 131]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.81       122
           1       0.85      0.85      0.85       154

    accuracy                           0.83       276
   macro avg       0.83      0.83      0.83       276
weighted avg       0.83      0.83      0.83       276

