In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report

In [10]:
def CNN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(22,1)))
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dense(7, activation='softmax'))

    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=10, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))
    return model

# Cleveland

In [11]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
model = CNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 1s 15ms/step - loss: 1.1441 - accuracy: 0.4340
Epoch 2/10
7/7 [==============================] - 0s 15ms/step - loss: 0.8049 - accuracy: 0.5000
Epoch 3/10
7/7 [==============================] - 0s 15ms/step - loss: 0.5968 - accuracy: 0.6698
Epoch 4/10
7/7 [==============================] - 0s 15ms/step - loss: 0.5223 - accuracy: 0.7594
Epoch 5/10
7/7 [==============================] - 0s 16ms/step - loss: 0.4831 - accuracy: 0.7736
Epoch 6/10
7/7 [==============================] - 0s 17ms/step - loss: 0.4606 - accuracy: 0.7877
Epoch 7/10
7/7 [==============================] - 0s 17ms/step - loss: 0.4474 - accuracy: 0.7925
Epoch 8/10
7/7 [==============================] - 0s 16ms/step - loss: 0.4358 - accuracy: 0.7925
Epoch 9/10
7/7 [==============================] - 0s 15ms/step - loss: 0.4148 - accuracy: 0.8302
Epoch 10/10
3/3 [==============================] - 0s 4ms/step
[[40  6]
 [11 34]]
              precision    recall  f1-score  

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
CNN(path_train,path_test)

Epoch 1/10
5/5 [==============================] - 1s 23ms/step - loss: 1.5135 - accuracy: 0.5286
Epoch 2/10
5/5 [==============================] - 0s 23ms/step - loss: 0.6122 - accuracy: 0.7286
Epoch 3/10
5/5 [==============================] - 0s 21ms/step - loss: 0.6442 - accuracy: 0.7286
Epoch 4/10
5/5 [==============================] - 0s 22ms/step - loss: 0.6120 - accuracy: 0.7143
Epoch 5/10
5/5 [==============================] - 0s 21ms/step - loss: 0.5545 - accuracy: 0.7286
Epoch 6/10
5/5 [==============================] - 0s 23ms/step - loss: 0.5570 - accuracy: 0.7286
Epoch 7/10
5/5 [==============================] - 0s 25ms/step - loss: 0.5458 - accuracy: 0.7286
Epoch 8/10
5/5 [==============================] - 0s 25ms/step - loss: 0.5574 - accuracy: 0.7286
Epoch 9/10
5/5 [==============================] - 0s 25ms/step - loss: 0.5404 - accuracy: 0.7357
Epoch 10/10
5/5 [==============================] - 0s 23ms/step - loss: 0.5359 - accuracy: 0.7286
[[ 0  0]
 [13 47]]
          

c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Europe

In [5]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
CNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 1s 20ms/step - loss: 1.0384 - accuracy: 0.5223
Epoch 2/10
10/10 [==============================] - 0s 20ms/step - loss: 0.5186 - accuracy: 0.7526
Epoch 3/10
10/10 [==============================] - 0s 20ms/step - loss: 0.5313 - accuracy: 0.7629
Epoch 4/10
10/10 [==============================] - 0s 20ms/step - loss: 0.4328 - accuracy: 0.7766
Epoch 5/10
10/10 [==============================] - 0s 23ms/step - loss: 0.4043 - accuracy: 0.8179
Epoch 6/10
10/10 [==============================] - 0s 21ms/step - loss: 0.3905 - accuracy: 0.8316
Epoch 7/10
10/10 [==============================] - 0s 21ms/step - loss: 0.3719 - accuracy: 0.8316
Epoch 8/10
10/10 [==============================] - 0s 23ms/step - loss: 0.3645 - accuracy: 0.8385
Epoch 9/10
10/10 [==============================] - 0s 23ms/step - loss: 0.3539 - accuracy: 0.8522
Epoch 10/10
10/10 [==============================] - 0s 26ms/step - loss: 0.3357 - accuracy: 0.8419
[[48  6]


# Combined

In [6]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
CNN(path_train,path_test)

Epoch 1/10
21/21 [==============================] - 1s 22ms/step - loss: 0.9234 - accuracy: 0.5202
Epoch 2/10
21/21 [==============================] - 0s 21ms/step - loss: 0.5885 - accuracy: 0.7096
Epoch 3/10
21/21 [==============================] - 0s 21ms/step - loss: 0.4718 - accuracy: 0.7655
Epoch 4/10
21/21 [==============================] - 0s 23ms/step - loss: 0.4920 - accuracy: 0.7655
Epoch 5/10
21/21 [==============================] - 1s 24ms/step - loss: 0.4571 - accuracy: 0.7935
Epoch 6/10
21/21 [==============================] - 0s 23ms/step - loss: 0.4630 - accuracy: 0.7811
Epoch 7/10
21/21 [==============================] - 0s 21ms/step - loss: 0.4333 - accuracy: 0.8152
Epoch 8/10
21/21 [==============================] - 0s 21ms/step - loss: 0.4401 - accuracy: 0.8043
Epoch 9/10
21/21 [==============================] - 0s 22ms/step - loss: 0.4547 - accuracy: 0.7966
Epoch 10/10
21/21 [==============================] - 0s 22ms/step - loss: 0.4124 - accuracy: 0.8230
[[ 99  21

In [5]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'

In [8]:
Train = pd.read_csv(path_train)
Test = pd.read_csv(path_test)
    
X_train = Train.iloc[:,:-1]
Y_train = Train.iloc[:,-1]

X_test = Test.iloc[:,:-1]
Y_test = Test.iloc[:,-1]

#binarize the target
Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

data = pd.concat([X_train,X_test])
labels = pd.concat([Y_train_binary,Y_test_binary])

data = data.reset_index()
data = data.drop(['index'],axis = 1)

labels = labels.reset_index()
labels = labels.iloc[:,-1]

labels

0      0
1      1
2      0
3      0
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: num, Length: 417, dtype: int64

In [12]:
Y_pred = model.predict(data).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, labels)
print(cm)
print(classification_report(labels, Y_pred))

14/14 [==============================] - 0s 4ms/step
[[ 53  30]
 [143 191]]
              precision    recall  f1-score   support

           0       0.64      0.27      0.38       196
           1       0.57      0.86      0.69       221

    accuracy                           0.59       417
   macro avg       0.61      0.57      0.53       417
weighted avg       0.60      0.59      0.54       417

