In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def CNN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(22,1)))
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dense(2, activation='sigmoid'))

    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=10, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))
    return model

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
model = CNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 2s 35ms/step - loss: 0.6428 - accuracy: 0.6132
Epoch 2/10
7/7 [==============================] - 0s 33ms/step - loss: 0.5864 - accuracy: 0.6981
Epoch 3/10
7/7 [==============================] - 0s 34ms/step - loss: 0.4864 - accuracy: 0.7547
Epoch 4/10
7/7 [==============================] - 0s 34ms/step - loss: 0.4794 - accuracy: 0.7689
Epoch 5/10
7/7 [==============================] - 0s 34ms/step - loss: 0.4356 - accuracy: 0.8113
Epoch 6/10
7/7 [==============================] - 0s 33ms/step - loss: 0.4279 - accuracy: 0.8113
Epoch 7/10
7/7 [==============================] - 0s 33ms/step - loss: 0.4148 - accuracy: 0.8066
Epoch 8/10
7/7 [==============================] - 0s 32ms/step - loss: 0.3979 - accuracy: 0.8208
Epoch 9/10
7/7 [==============================] - 0s 34ms/step - loss: 0.4012 - accuracy: 0.8208
Epoch 10/10
7/7 [==============================] - 0s 31ms/step - loss: 0.3826 - accuracy: 0.8160
[[42  6]
 [ 9 34]]
          

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
CNN(path_train,path_test)

Epoch 1/10
5/5 [==============================] - 1s 32ms/step - loss: 0.6151 - accuracy: 0.7286
Epoch 2/10
5/5 [==============================] - 0s 30ms/step - loss: 0.6403 - accuracy: 0.7286
Epoch 3/10
5/5 [==============================] - 0s 30ms/step - loss: 0.5874 - accuracy: 0.7286
Epoch 4/10
5/5 [==============================] - 0s 31ms/step - loss: 0.5656 - accuracy: 0.7286
Epoch 5/10
5/5 [==============================] - 0s 31ms/step - loss: 0.5448 - accuracy: 0.7286
Epoch 6/10
5/5 [==============================] - 0s 29ms/step - loss: 0.5372 - accuracy: 0.7286
Epoch 7/10
5/5 [==============================] - 0s 30ms/step - loss: 0.5259 - accuracy: 0.7286
Epoch 8/10
5/5 [==============================] - 0s 31ms/step - loss: 0.5067 - accuracy: 0.7357
Epoch 9/10
5/5 [==============================] - 0s 29ms/step - loss: 0.4979 - accuracy: 0.8000
Epoch 10/10
5/5 [==============================] - 0s 31ms/step - loss: 0.5184 - accuracy: 0.7357
[[ 2  1]
 [11 46]]
          

# Europe

In [5]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
CNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 1s 31ms/step - loss: 0.5859 - accuracy: 0.7079
Epoch 2/10
10/10 [==============================] - 0s 32ms/step - loss: 0.4282 - accuracy: 0.8041
Epoch 3/10
10/10 [==============================] - 0s 31ms/step - loss: 0.4119 - accuracy: 0.8385
Epoch 4/10
10/10 [==============================] - 0s 31ms/step - loss: 0.4820 - accuracy: 0.8007
Epoch 5/10
10/10 [==============================] - 0s 30ms/step - loss: 0.4057 - accuracy: 0.8247
Epoch 6/10
10/10 [==============================] - 0s 31ms/step - loss: 0.3451 - accuracy: 0.8488
Epoch 7/10
10/10 [==============================] - 0s 31ms/step - loss: 0.3456 - accuracy: 0.8419
Epoch 8/10
10/10 [==============================] - 0s 40ms/step - loss: 0.3272 - accuracy: 0.8522
Epoch 9/10
10/10 [==============================] - 0s 29ms/step - loss: 0.3404 - accuracy: 0.8591
Epoch 10/10
10/10 [==============================] - 0s 28ms/step - loss: 0.3552 - accuracy: 0.8385
[[48  9]


# Combined

In [6]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
CNN(path_train,path_test)

Epoch 1/10
21/21 [==============================] - 2s 31ms/step - loss: 0.6165 - accuracy: 0.6429
Epoch 2/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4819 - accuracy: 0.7717
Epoch 3/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4545 - accuracy: 0.7811
Epoch 4/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4425 - accuracy: 0.8106
Epoch 5/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4172 - accuracy: 0.8152
Epoch 6/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4138 - accuracy: 0.8307
Epoch 7/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4197 - accuracy: 0.8106
Epoch 8/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4176 - accuracy: 0.8168
Epoch 9/10
21/21 [==============================] - 1s 32ms/step - loss: 0.3918 - accuracy: 0.8276
Epoch 10/10
21/21 [==============================] - 1s 32ms/step - loss: 0.4004 - accuracy: 0.8214
[[ 94  12

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'

In [8]:
Train = pd.read_csv(path_train)
Test = pd.read_csv(path_test)
    
X_train = Train.iloc[:,:-1]
Y_train = Train.iloc[:,-1]

X_test = Test.iloc[:,:-1]
Y_test = Test.iloc[:,-1]

#binarize the target
Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

data = pd.concat([X_train,X_test])
labels = pd.concat([Y_train_binary,Y_test_binary])

data = data.reset_index()
data = data.drop(['index'],axis = 1)

labels = labels.reset_index()
labels = labels.iloc[:,-1]

labels

0      0
1      1
2      0
3      0
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: num, Length: 417, dtype: int64

In [9]:
Y_pred = model.predict(data).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, labels)
print(cm)
print(classification_report(labels, Y_pred))

[[ 64  25]
 [132 196]]
              precision    recall  f1-score   support

           0       0.72      0.33      0.45       196
           1       0.60      0.89      0.71       221

    accuracy                           0.62       417
   macro avg       0.66      0.61      0.58       417
weighted avg       0.65      0.62      0.59       417

