In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def CNN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu', input_shape=(22,1)))
    model.add(Conv1D(filters=256, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Conv1D(filters=512, kernel_size=3, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dense(2, activation='sigmoid'))

    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=10, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))
    return model

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
model = CNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 1s 22ms/step - loss: 0.6838 - accuracy: 0.5613
Epoch 2/10
7/7 [==============================] - 0s 24ms/step - loss: 0.5425 - accuracy: 0.7594
Epoch 3/10
7/7 [==============================] - 0s 24ms/step - loss: 0.5007 - accuracy: 0.7406
Epoch 4/10
7/7 [==============================] - 0s 23ms/step - loss: 0.4797 - accuracy: 0.7925
Epoch 5/10
7/7 [==============================] - 0s 23ms/step - loss: 0.4437 - accuracy: 0.8160
Epoch 6/10
7/7 [==============================] - 0s 24ms/step - loss: 0.4286 - accuracy: 0.7830
Epoch 7/10
7/7 [==============================] - 0s 25ms/step - loss: 0.4064 - accuracy: 0.8019
Epoch 8/10
7/7 [==============================] - 0s 24ms/step - loss: 0.3886 - accuracy: 0.8208
Epoch 9/10
7/7 [==============================] - 0s 24ms/step - loss: 0.3786 - accuracy: 0.8349
Epoch 10/10
7/7 [==============================] - 0s 25ms/step - loss: 0.3704 - accuracy: 0.8255
[[38  5]
 [13 35]]
          

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
CNN(path_train,path_test)

Epoch 1/10
5/5 [==============================] - 1s 23ms/step - loss: 0.6168 - accuracy: 0.7286
Epoch 2/10
5/5 [==============================] - 0s 23ms/step - loss: 0.5824 - accuracy: 0.7286
Epoch 3/10
5/5 [==============================] - 0s 24ms/step - loss: 0.5891 - accuracy: 0.7286
Epoch 4/10
5/5 [==============================] - 0s 24ms/step - loss: 0.5820 - accuracy: 0.7286
Epoch 5/10
5/5 [==============================] - 0s 25ms/step - loss: 0.5610 - accuracy: 0.7286
Epoch 6/10
5/5 [==============================] - 0s 23ms/step - loss: 0.5522 - accuracy: 0.7286
Epoch 7/10
5/5 [==============================] - 0s 25ms/step - loss: 0.5495 - accuracy: 0.7286
Epoch 8/10
5/5 [==============================] - 0s 24ms/step - loss: 0.5228 - accuracy: 0.7286
Epoch 9/10
5/5 [==============================] - 0s 24ms/step - loss: 0.5069 - accuracy: 0.7286
Epoch 10/10
5/5 [==============================] - 0s 25ms/step - loss: 0.4910 - accuracy: 0.7714
[[ 3  1]
 [10 46]]
          

# Hungary

In [5]:
path_train = '../traintestdata/hun_train.csv'
path_test = '../traintestdata/hun_test.csv'
CNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 1s 22ms/step - loss: 0.6258 - accuracy: 0.6488
Epoch 2/10
7/7 [==============================] - 0s 23ms/step - loss: 0.4242 - accuracy: 0.8341
Epoch 3/10
7/7 [==============================] - 0s 25ms/step - loss: 0.3899 - accuracy: 0.7951
Epoch 4/10
7/7 [==============================] - 0s 24ms/step - loss: 0.3427 - accuracy: 0.8341
Epoch 5/10
7/7 [==============================] - 0s 22ms/step - loss: 0.3234 - accuracy: 0.8390
Epoch 6/10
7/7 [==============================] - 0s 23ms/step - loss: 0.3403 - accuracy: 0.8293
Epoch 7/10
7/7 [==============================] - 0s 25ms/step - loss: 0.2994 - accuracy: 0.8390
Epoch 8/10
7/7 [==============================] - 0s 24ms/step - loss: 0.2997 - accuracy: 0.8829
Epoch 9/10
7/7 [==============================] - 0s 23ms/step - loss: 0.3063 - accuracy: 0.8439
Epoch 10/10
7/7 [==============================] - 0s 27ms/step - loss: 0.2589 - accuracy: 0.9024
[[54  9]
 [ 3 23]]
          

# Switzerland

In [6]:
path_train = '../traintestdata/swi_train.csv'
path_test = '../traintestdata/swi_test.csv'
CNN(path_train,path_test)

Epoch 1/10
3/3 [==============================] - 1s 26ms/step - loss: 0.5478 - accuracy: 0.6047
Epoch 2/10
3/3 [==============================] - 0s 28ms/step - loss: 0.2909 - accuracy: 0.9302
Epoch 3/10
3/3 [==============================] - 0s 26ms/step - loss: 0.2672 - accuracy: 0.9302
Epoch 4/10
3/3 [==============================] - 0s 26ms/step - loss: 0.2553 - accuracy: 0.9302
Epoch 5/10
3/3 [==============================] - 0s 25ms/step - loss: 0.2383 - accuracy: 0.9302
Epoch 6/10
3/3 [==============================] - 0s 24ms/step - loss: 0.2498 - accuracy: 0.9302
Epoch 7/10
3/3 [==============================] - 0s 28ms/step - loss: 0.2335 - accuracy: 0.9302
Epoch 8/10
3/3 [==============================] - 0s 29ms/step - loss: 0.2265 - accuracy: 0.9302
Epoch 9/10
3/3 [==============================] - 0s 29ms/step - loss: 0.2130 - accuracy: 0.9302
Epoch 10/10
3/3 [==============================] - 0s 27ms/step - loss: 0.2048 - accuracy: 0.9302
[[ 0  0]
 [ 2 35]]
          

c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\votri\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Europe

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
CNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 1s 25ms/step - loss: 0.5603 - accuracy: 0.6907
Epoch 2/10
10/10 [==============================] - 0s 24ms/step - loss: 0.4161 - accuracy: 0.8282
Epoch 3/10
10/10 [==============================] - 0s 22ms/step - loss: 0.4410 - accuracy: 0.8041
Epoch 4/10
10/10 [==============================] - 0s 23ms/step - loss: 0.3721 - accuracy: 0.8282
Epoch 5/10
10/10 [==============================] - 0s 23ms/step - loss: 0.3583 - accuracy: 0.8385
Epoch 6/10
10/10 [==============================] - 0s 23ms/step - loss: 0.3487 - accuracy: 0.8316
Epoch 7/10
10/10 [==============================] - 0s 22ms/step - loss: 0.3513 - accuracy: 0.8454
Epoch 8/10
10/10 [==============================] - 0s 32ms/step - loss: 0.3350 - accuracy: 0.8522
Epoch 9/10
10/10 [==============================] - 0s 34ms/step - loss: 0.3350 - accuracy: 0.8660
Epoch 10/10
10/10 [==============================] - 0s 34ms/step - loss: 0.3163 - accuracy: 0.8522
[[50  9]


# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
CNN(path_train,path_test)

Epoch 1/10
21/21 [==============================] - 2s 35ms/step - loss: 0.6257 - accuracy: 0.6630
Epoch 2/10
21/21 [==============================] - 1s 37ms/step - loss: 0.5014 - accuracy: 0.7609
Epoch 3/10
21/21 [==============================] - 1s 35ms/step - loss: 0.4734 - accuracy: 0.7748
Epoch 4/10
21/21 [==============================] - 1s 27ms/step - loss: 0.4672 - accuracy: 0.7873
Epoch 5/10
21/21 [==============================] - 1s 26ms/step - loss: 0.4312 - accuracy: 0.7950
Epoch 6/10
21/21 [==============================] - 1s 27ms/step - loss: 0.4282 - accuracy: 0.8168
Epoch 7/10
21/21 [==============================] - 1s 34ms/step - loss: 0.4316 - accuracy: 0.8121
Epoch 8/10
21/21 [==============================] - 1s 24ms/step - loss: 0.4061 - accuracy: 0.8307
Epoch 9/10
21/21 [==============================] - 1s 28ms/step - loss: 0.4166 - accuracy: 0.8214
Epoch 10/10
21/21 [==============================] - 1s 32ms/step - loss: 0.3879 - accuracy: 0.8261
[[100  20

In [9]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'

In [10]:
Train = pd.read_csv(path_train)
Test = pd.read_csv(path_test)
    
X_train = Train.iloc[:,:-1]
Y_train = Train.iloc[:,-1]

X_test = Test.iloc[:,:-1]
Y_test = Test.iloc[:,-1]

#binarize the target
Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

data = pd.concat([X_train,X_test])
labels = pd.concat([Y_train_binary,Y_test_binary])

data = data.reset_index()
data = data.drop(['index'],axis = 1)

labels = labels.reset_index()
labels = labels.iloc[:,-1]

labels

0      0
1      1
2      0
3      0
4      0
      ..
412    1
413    1
414    1
415    1
416    1
Name: num, Length: 417, dtype: int64

In [11]:
Y_pred = model.predict(data).argmax(axis=1)
    
cm = confusion_matrix(Y_pred, labels)
print(cm)
print(classification_report(labels, Y_pred))

[[ 55  15]
 [141 206]]
              precision    recall  f1-score   support

           0       0.79      0.28      0.41       196
           1       0.59      0.93      0.73       221

    accuracy                           0.63       417
   macro avg       0.69      0.61      0.57       417
weighted avg       0.68      0.63      0.58       417

