In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
def RandomForest(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    #Bayesian Classifier
    classifier = RandomForestClassifier(n_estimators=100, random_state=42)
    classifier.fit(X_train, Y_train_binary)
    Y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [4]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
RandomForest(path_train,path_test)

[[41  5]
 [10 35]]
              precision    recall  f1-score   support

           0       0.89      0.80      0.85        51
           1       0.78      0.88      0.82        40

    accuracy                           0.84        91
   macro avg       0.83      0.84      0.83        91
weighted avg       0.84      0.84      0.84        91



# Virginia

In [6]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
RandomForest(path_train,path_test)

[[ 6  3]
 [ 7 44]]
              precision    recall  f1-score   support

           0       0.67      0.46      0.55        13
           1       0.86      0.94      0.90        47

    accuracy                           0.83        60
   macro avg       0.76      0.70      0.72        60
weighted avg       0.82      0.83      0.82        60



# European

In [7]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
RandomForest(path_train,path_test)

[[53  6]
 [ 6 61]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        59
           1       0.91      0.91      0.91        67

    accuracy                           0.90       126
   macro avg       0.90      0.90      0.90       126
weighted avg       0.90      0.90      0.90       126



# Combined

In [8]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
RandomForest(path_train,path_test)

[[101  20]
 [ 21 134]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       122
           1       0.86      0.87      0.87       154

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276

