In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
def RNN(path_train,path_test):
    #Split the data
    Train = pd.read_csv(path_train)
    Test = pd.read_csv(path_test)
    
    X_train = Train.iloc[:,:-1]
    Y_train = Train.iloc[:,-1]

    X_test = Test.iloc[:,:-1]
    Y_test = Test.iloc[:,-1]

    #binarize the target
    Y_train_binary = Y_train.apply(lambda x: 1 if x > 0 else 0)
    Y_test_binary = Y_test.apply(lambda x: 1 if x > 0 else 0)

    # define the model architecture
    model = Sequential()
    model.add(SimpleRNN(units=64, return_sequences=True, input_shape=(22, 1)))
    model.add(SimpleRNN(units=32, return_sequences=True))
    model.add(SimpleRNN(units=16))
    model.add(Dense(units=2, activation='sigmoid'))
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    model.fit(X_train, Y_train_binary, epochs=10, batch_size=32)
    Y_pred = model.predict(X_test).argmax(axis=1)
    
    cm = confusion_matrix(Y_pred, Y_test_binary)
    print(cm)
    print(classification_report(Y_test_binary, Y_pred))

# Cleveland

In [3]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/cle_test.csv'
RNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 2s 15ms/step - loss: 0.6124 - accuracy: 0.6179
Epoch 2/10
7/7 [==============================] - 0s 14ms/step - loss: 0.4268 - accuracy: 0.7830
Epoch 3/10
7/7 [==============================] - 0s 15ms/step - loss: 0.4073 - accuracy: 0.8066
Epoch 4/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3824 - accuracy: 0.8396
Epoch 5/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3699 - accuracy: 0.8160
Epoch 6/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3493 - accuracy: 0.8302
Epoch 7/10
7/7 [==============================] - 0s 16ms/step - loss: 0.3354 - accuracy: 0.8443
Epoch 8/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3289 - accuracy: 0.8538
Epoch 9/10
7/7 [==============================] - 0s 13ms/step - loss: 0.3183 - accuracy: 0.8679
Epoch 10/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3180 - accuracy: 0.8491
[[38  6]
 [13 34]]
          

# Virginia

In [4]:
path_train = '../traintestdata/vir_train.csv'
path_test = '../traintestdata/vir_test.csv'
RNN(path_train,path_test)

Epoch 1/10
5/5 [==============================] - 2s 16ms/step - loss: 0.6452 - accuracy: 0.6786
Epoch 2/10
5/5 [==============================] - 0s 16ms/step - loss: 0.5450 - accuracy: 0.7214
Epoch 3/10
5/5 [==============================] - 0s 16ms/step - loss: 0.5090 - accuracy: 0.7429
Epoch 4/10
5/5 [==============================] - 0s 16ms/step - loss: 0.4945 - accuracy: 0.7500
Epoch 5/10
5/5 [==============================] - 0s 15ms/step - loss: 0.4753 - accuracy: 0.7643
Epoch 6/10
5/5 [==============================] - 0s 15ms/step - loss: 0.4644 - accuracy: 0.7786
Epoch 7/10
5/5 [==============================] - 0s 15ms/step - loss: 0.4498 - accuracy: 0.7643
Epoch 8/10
5/5 [==============================] - 0s 15ms/step - loss: 0.4371 - accuracy: 0.8071
Epoch 9/10
5/5 [==============================] - 0s 15ms/step - loss: 0.4315 - accuracy: 0.8000
Epoch 10/10
5/5 [==============================] - 0s 14ms/step - loss: 0.4157 - accuracy: 0.8071
[[ 3  4]
 [10 43]]
          

# Europe

In [5]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/euro_test.csv'
RNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 2s 15ms/step - loss: 0.5500 - accuracy: 0.7045
Epoch 2/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3974 - accuracy: 0.8144
Epoch 3/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3629 - accuracy: 0.8385
Epoch 4/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3476 - accuracy: 0.8625
Epoch 5/10
10/10 [==============================] - 0s 42ms/step - loss: 0.3156 - accuracy: 0.8763
Epoch 6/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3006 - accuracy: 0.8763
Epoch 7/10
10/10 [==============================] - 0s 14ms/step - loss: 0.2957 - accuracy: 0.8660
Epoch 8/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3399 - accuracy: 0.8522
Epoch 9/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3032 - accuracy: 0.8729
Epoch 10/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3437 - accuracy: 0.8557
[[50  7]


# Combined

In [6]:
path_train = '../traintestdata/com_train.csv'
path_test = '../traintestdata/com_test.csv'
RNN(path_train,path_test)

Epoch 1/10
21/21 [==============================] - 2s 13ms/step - loss: 0.5782 - accuracy: 0.7314
Epoch 2/10
21/21 [==============================] - 0s 14ms/step - loss: 0.4574 - accuracy: 0.7857
Epoch 3/10
21/21 [==============================] - 0s 13ms/step - loss: 0.4306 - accuracy: 0.7981
Epoch 4/10
21/21 [==============================] - 0s 14ms/step - loss: 0.4360 - accuracy: 0.7904
Epoch 5/10
21/21 [==============================] - 0s 13ms/step - loss: 0.4049 - accuracy: 0.8214
Epoch 6/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3938 - accuracy: 0.8230
Epoch 7/10
21/21 [==============================] - 0s 15ms/step - loss: 0.3866 - accuracy: 0.8245
Epoch 8/10
21/21 [==============================] - 0s 14ms/step - loss: 0.3824 - accuracy: 0.8245
Epoch 9/10
21/21 [==============================] - 0s 13ms/step - loss: 0.3809 - accuracy: 0.8307
Epoch 10/10
21/21 [==============================] - 0s 13ms/step - loss: 0.3842 - accuracy: 0.8323
[[ 92  11

# Testing models on different data

In [7]:
path_train = '../traintestdata/cle_train.csv'
path_test = '../traintestdata/euro_test.csv'
RNN(path_train,path_test)

Epoch 1/10
7/7 [==============================] - 2s 15ms/step - loss: 0.5908 - accuracy: 0.7170
Epoch 2/10
7/7 [==============================] - 0s 14ms/step - loss: 0.4651 - accuracy: 0.8113
Epoch 3/10
7/7 [==============================] - 0s 13ms/step - loss: 0.4169 - accuracy: 0.8066
Epoch 4/10
7/7 [==============================] - 0s 15ms/step - loss: 0.4021 - accuracy: 0.8066
Epoch 5/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3738 - accuracy: 0.8113
Epoch 6/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3737 - accuracy: 0.8302
Epoch 7/10
7/7 [==============================] - 0s 13ms/step - loss: 0.3491 - accuracy: 0.8349
Epoch 8/10
7/7 [==============================] - 0s 15ms/step - loss: 0.3478 - accuracy: 0.8443
Epoch 9/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3292 - accuracy: 0.8396
Epoch 10/10
7/7 [==============================] - 0s 14ms/step - loss: 0.3292 - accuracy: 0.8585
[[45  6]
 [14 61]]
          

In [8]:
path_train = '../traintestdata/euro_train.csv'
path_test = '../traintestdata/cle_test.csv'
RNN(path_train,path_test)

Epoch 1/10
10/10 [==============================] - 2s 15ms/step - loss: 0.5229 - accuracy: 0.7457
Epoch 2/10
10/10 [==============================] - 0s 14ms/step - loss: 0.4231 - accuracy: 0.8213
Epoch 3/10
10/10 [==============================] - 0s 15ms/step - loss: 0.3935 - accuracy: 0.8557
Epoch 4/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3444 - accuracy: 0.8385
Epoch 5/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3420 - accuracy: 0.8454
Epoch 6/10
10/10 [==============================] - 0s 13ms/step - loss: 0.3189 - accuracy: 0.8557
Epoch 7/10
10/10 [==============================] - 0s 13ms/step - loss: 0.3151 - accuracy: 0.8660
Epoch 8/10
10/10 [==============================] - 0s 14ms/step - loss: 0.3051 - accuracy: 0.8660
Epoch 9/10
10/10 [==============================] - 0s 15ms/step - loss: 0.2870 - accuracy: 0.8900
Epoch 10/10
10/10 [==============================] - 0s 16ms/step - loss: 0.2820 - accuracy: 0.8832
[[24  3]
